/**
 * Rules the Control Panel (A-01..A-49) implements or displays. Ids from docs/rules/business-rules-from-designs.md where
 * a design rule exists; owner rules for this module use R-X40..R-X49 (the A-4x range) so they never clash with other modules.
 */
import { defineRules } from './types';

export const rules = defineRules([
  { id: 'R-K03', title: 'Company profile with one legal address', description: 'Company name, legal name, address, phone, email and website are edited in one place (Company & locations) and printed on invoices.', category: 'locations', status: 'implemented', pages: ['A-10', 'A-44'], source: '1.pdf, 2.pdf', implementedIn: 'settings.company (A-10)' },
  { id: 'R-K04', title: 'Per-location working hours by weekday', description: 'Each location has an open flag and open / close time per weekday; closed days are null. Front desk and customer surfaces read these hours.', category: 'locations', status: 'implemented', pages: ['A-10', 'A-11', 'A-41'], source: '3.pdf, front desk-7.jpg', implementedIn: 'locations.hours edited by AdminHoursGrid' },
  { id: 'R-K06', title: 'Brand setup: logo, font, colours', description: 'Owner can upload a logo (mock), pick the font (Inter only for now) and the primary / background colours. Tokens stay the single source; the brand form writes settings.brand.', category: 'account', status: 'in_dev', pages: ['A-44'], source: '1.pdf', implementedIn: 'settings.brand (A-44); token wiring pending' },
  { id: 'R-J10', title: 'General settings: time format, slot interval, weight unit, defaults', description: '12 / 24 h time format, calendar slot minutes, weight unit (lbs), default pet type and contact method live in settings.general.', category: 'account', status: 'implemented', pages: ['A-44'], source: '7.pdf', implementedIn: 'settings.general (A-44)' },
  { id: 'R-H12', title: 'Payment processing provider is configurable', description: 'The Control Panel shows the payment provider seam (mock today, Stripe Elements later) with no keys stored in the app.', category: 'fees_tax', status: 'in_dev', pages: ['A-28'], source: '9.pdf', implementedIn: 'src/payments (StripePaymentProvider stub)' },
  { id: 'R-M13', title: 'Email / SMS / push providers with test-send', description: 'Owner configures the outbound channels (None / Gmail / SMTP, None / Twilio / Petlinx, None / FCM / APNs) and can send a test message. Stubs until an integration exists.', category: 'account', status: 'in_dev', pages: ['A-28'], source: '5.pdf', implementedIn: 'providers table (A-28)' },
  { id: 'R-L06', title: 'Add-ons can be restricted to an employee type', description: 'Add-ons carry an employee_type (e.g. special employee for internal gland expression); the grooming day view only offers them to matching staff.', category: 'grooming', status: 'in_dev', pages: ['A-25', 'F-30'], source: 'front desk-6.jpg', implementedIn: 'addons.employee_type (A-25)' },
  { id: 'R-H11', title: 'Customers can carry an outstanding balance', description: 'customers.balance is shown in reports and the dashboard; the owner sees who owes what.', category: 'operations', status: 'in_dev', pages: ['A-42'], source: '6.pdf', implementedIn: 'customers.balance (A-42 reports)' },
  { id: 'R-X40', title: 'Per-role side menu is owner-configurable', description: 'The owner hides or shows menu categories per role (D-014). Stored in roles.menu as category -> visible; the shell reads it on top of the permission filter.', category: 'people', status: 'in_dev', pages: ['A-32'], source: 'D-014, prompt 0005', implementedIn: 'roles.menu (A-32); DesktopShell read pending' },
  { id: 'R-X41', title: 'Every Control Panel change is written to the audit log', description: 'Insert / update / delete of any settings, pricing, staff or role row writes an audit_log row with the diff and the actor.', category: 'operations', status: 'implemented', pages: ['A-38', 'A-10', 'A-11', 'A-12', 'A-20', 'A-21', 'A-22', 'A-23', 'A-24', 'A-25', 'A-26', 'A-28', 'A-30', 'A-31', 'A-32', 'A-44'], source: 'prompt 0005 (audit log & approvals log)', implementedIn: 'useAdminAudit() in src/modules/admin-control-panel' },
  { id: 'R-X42', title: 'Deleting a settings or staff record needs a manager PIN', description: 'Removing a room, rate, discount, package, add-on, employee or location opens PinApprovalModal and writes an approvals row first (extends R-P01 to the Control Panel).', category: 'pin_approvals', status: 'implemented', pages: ['A-12', 'A-20', 'A-21', 'A-22', 'A-23', 'A-24', 'A-25', 'A-26', 'A-30', 'A-11'], source: 'prompt 0005 (deleting records)', implementedIn: 'AdminRecordDrawer delete -> PinApprovalModal' },
  { id: 'R-X43', title: 'Setting or resetting a staff PIN needs a manager PIN', description: 'A new 4-6 digit PIN for an employee is stored hashed; the change is approved by a manager / owner PIN and audited.', category: 'pin_approvals', status: 'implemented', pages: ['A-30'], source: 'prompt 0005 (PIN set / reset)', implementedIn: 'A-30 EmployeesPage' },
  { id: 'R-X44', title: 'Pricing pages never hardcode a price', description: 'Room rates, discounts, fees, taxes, daycare and grooming prices come only from their tables; the pricing preview quotes through src/pricing/engine.ts.', category: 'pricing', status: 'implemented', pages: ['A-20', 'A-21', 'A-22', 'A-23', 'A-24', 'A-25', 'A-27'], source: 'CLAUDE.md pricing rule', implementedIn: 'A-27 PricingPreviewPage uses quoteHotel / quoteGrooming / quoteDaycare' },
  { id: 'R-X45', title: 'Reports and exports respect the location scope', description: 'Reports aggregate the current location, or all locations when the owner chooses All; CSV exports contain exactly the rows shown.', category: 'operations', status: 'implemented', pages: ['A-42', 'A-01'], source: 'prompt 0005 (reports & analytics)', implementedIn: 'A-42 ReportsPage' },
  { id: 'R-X46', title: 'Adding a location is a settings flow, never code', description: 'A new location inserts a locations row plus four capacities rows (penthouse, suite, daycare, grooming); every scoped table follows it.', category: 'locations', status: 'implemented', pages: ['A-41', 'A-10'], source: 'D-019, project brief', implementedIn: 'A-41 AddLocationPage' },
  { id: 'R-X47', title: 'Published reviews can be unpublished', description: 'Review moderation: pending -> published or archived; a published review can go back to pending or archived (answers open question 111). Moderation needs reviews.moderate.', category: 'operations', status: 'implemented', pages: ['A-35'], source: 'reviews.jpg, open question 111', implementedIn: 'A-35 ReviewsPage' },
  { id: 'R-X48', title: 'Feedback has a lifecycle new -> seen -> done with an owner reply', description: 'Opening a feedback item marks it seen; the owner can reply and close it. Feedback stays visible to the author role on the page it was left from (later).', category: 'operations', status: 'implemented', pages: ['A-36'], source: 'project brief (feedback inbox)', implementedIn: 'A-36 FeedbackInboxPage' },
  { id: 'R-X49', title: 'Role permissions are editable in a matrix, super admin always keeps everything', description: 'The permissions table is the runtime source; the matrix edits it per role. super_admin is read-only and owner cannot remove its own settings.write.', category: 'people', status: 'in_dev', pages: ['A-31'], source: '10.pdf, R-L05', implementedIn: 'permissions table (A-31); SessionProvider still reads ROLE_PERMISSIONS' },
]);
