import { defineRules } from './types';

/**
 * Customer auth rules (C-01..C-09). R-M14 / R-M15 come from the design read; R-X30..R-X39 are the best-practice
 * rules D-018 allows (the auth range is reserved so parallel modules do not collide on R-X ids).
 */
export const rules = defineRules([
  { id: 'R-M14', title: 'Sign-up placeholder hints', description: 'Inputs show example values (e.g. Merry, Jonas, merry@example.com). Password placeholder from Figma (#123@156) replaced by the policy hint (R-X30).', category: 'account', status: 'implemented', pages: ['C-02', 'C-03', 'C-05'], source: 'Frame 1171276421.png (D-018)', implementedIn: 'src/modules/customer-auth strings' },
  { id: 'R-M15', title: 'Password reset copy', description: 'Figma "Forget password / To reset your new password please enter your email address" corrected to "Forgot your password? Enter the email you signed up with and we will send a 6-digit code."', category: 'account', status: 'implemented', pages: ['C-05', 'C-06'], source: 'Frame 1171276423.png (copy fix)', implementedIn: 'C-05 ForgotPasswordPage' },
  { id: 'R-X30', title: 'Password policy: at least 8 characters with a letter and a number', description: 'settings.auth.policy.passwordMinLength (default 8). The field shows a live strength meter and checklist; common passwords (password, 12345678, petrock) are rejected. No forced symbols, no expiry (NIST 800-63B).', category: 'account', status: 'implemented', pages: ['C-03', 'C-06'], source: 'D-018 best practice', implementedIn: 'src/modules/customer-auth/passwordPolicy.ts' },
  { id: 'R-X31', title: 'Lock the account after 5 failed sign-ins for 15 minutes', description: 'auth_credentials.failed_attempts and locked_until; thresholds from settings.auth.policy. While locked, sign-in shows C-07 with the remaining time; a password reset clears the lock.', category: 'account', status: 'implemented', pages: ['C-02', 'C-07'], source: 'D-018 best practice', implementedIn: 'authService.signIn' },
  { id: 'R-X32', title: 'One-time codes: 6 digits, 10 minutes, 5 attempts, resend after 30 s', description: 'auth_codes rows; issuing a new code consumes the previous live one for the same email + purpose. Delivery is mocked (the demo shows the code in a toast); production sends email/SMS through Company-OS.', category: 'account', status: 'implemented', pages: ['C-04', 'C-06'], source: 'D-010 (OTP modal), D-018', implementedIn: 'authService.issueCode / verifyCode' },
  { id: 'R-X33', title: 'Email must be verified before the first booking', description: 'A customer can sign in with an unverified email (C-02 opens the verify modal) and browse; the booking flows check auth_credentials.email_verified and send the customer to C-04 before payment.', category: 'account', status: 'in_dev', pages: ['C-02', 'C-04', 'C-30', 'C-50', 'C-60'], source: 'D-018 best practice' },
  { id: 'R-X34', title: 'Forgot password never reveals whether an email exists', description: 'C-05 always shows "If an account exists for {email} we sent a code"; the code is only issued for known emails. The demo hint is shown only in the mock provider.', category: 'account', status: 'implemented', pages: ['C-05'], source: 'D-018 best practice (no account enumeration)', implementedIn: 'authService.requestPasswordReset' },
  { id: 'R-X35', title: 'Remember me keeps the session 30 days; otherwise it ends with the browser session', description: 'auth_credentials.remember_me and settings.auth.policy.rememberDays. Stored today; enforcement needs a session-expiry check in SessionProvider (foundation).', category: 'account', status: 'in_dev', pages: ['C-02'], source: 'Frame 1171276422.png (Remember me toggle)' },
  { id: 'R-X36', title: 'Sign-up creates users + customers + auth_credentials together', description: 'One customer household per account; role customer; home location chosen at sign-up (Encino / Westwood) becomes customers.home_location_id. Duplicate email is refused with a link to sign in.', category: 'account', status: 'implemented', pages: ['C-03'], source: 'entities 1 & 20; D-019 locations', implementedIn: 'authService.signUp' },
  { id: 'R-X37', title: 'Every auth action is logged to auth_events', description: 'sign_up, email_verified, sign_in, sign_in_failed, locked, sign_out, otp_sent, otp_failed, password_reset_requested, password_reset with the page code. Owner reports can read it.', category: 'account', status: 'implemented', pages: ['C-02', 'C-03', 'C-04', 'C-05', 'C-06', 'C-09'], source: 'D-018 best practice', implementedIn: 'authService.logEvent' },
  { id: 'R-X38', title: 'Terms and privacy must be accepted at sign-up', description: 'Required checkbox; auth_credentials.terms_accepted_at records when. Marketing opt-in is a separate optional checkbox (customers.marketing_opt_in).', category: 'account', status: 'implemented', pages: ['C-03'], source: 'app-store requirements; D-018', implementedIn: 'C-03 SignUpPage' },
  { id: 'R-X39', title: 'Account deletion and support contact live in the customer settings', description: 'Deleting an account re-authenticates (password or code) and creates a deletion request the owner reviews; help / contact is in the settings hub. Built by the customer-settings-chat module (C-70..C-79); C-07 links there.', category: 'account', status: 'requested', pages: ['C-07', 'C-70'], source: 'R-M05, open question 15' },
]);
