/**
 * Rules implemented by the customer-settings-chat module (C-70..C-89). Reuses R-M ids from
 * docs/rules/business-rules-from-designs.md that were not yet in code; new rules take R-M20+ (account & chat range).
 * R-M03, R-M04, R-M05 and R-M09 already live in operations.ts (statuses to update at merge: see the pending changelog).
 */
import { defineRules } from './types';

export const rules = defineRules([
  { id: 'R-M01', title: 'Email and password are changed through separate flows', description: 'Edit profile shows email read-only with "Change email" (confirmation modal) and a disabled masked password with "Change password" (own screen). Never edited inline.', category: 'account', status: 'implemented', pages: ['C-71', 'C-84'], source: 'image 175.png, Frame 1171276433.png', implementedIn: 'src/modules/customer-settings-chat/EditProfilePage.tsx' },
  { id: 'R-M06', title: 'Profile hub menu', description: 'Edit profile, My pets, Payment methods, Notifications, Front Desk chat, App settings, Help & support, Rate the app, About & legal, Log out. Figma "Add Pets" and "Invite Friend" dropped (open question 62); "Address" folded into Edit profile.', category: 'account', status: 'implemented', pages: ['C-70'], source: 'profile.jpg, Frame 1171276432.png', implementedIn: 'ProfileHubPage.tsx' },
  { id: 'R-M07', title: 'Notification kinds', description: 'booking_confirmed, checkin_reminder, payment, receipt, vaccine_expiring, vaccine_verified, pet_added, chat, photo, promo. UI-kit leftovers (orders, deliveries, vet appointments) are not kinds.', category: 'account', status: 'implemented', pages: ['C-80', 'F-60'], source: 'notification.png', implementedIn: 'NotificationRow kind -> icon map' },
  { id: 'R-M08', title: 'Relative timestamps for notifications and chat', description: 'Just now, 5 min ago, 3 h ago, Yesterday, weekday within 7 days, then "Sep 3"; consistent grammar (fixes the Figma "3 Hour Ago").', category: 'account', status: 'implemented', pages: ['C-80', 'C-81', 'C-82'], source: 'notification.png, message-1.jpg', implementedIn: 'src/modules/customer-settings-chat/time.ts' },
  { id: 'R-M10', title: 'Chat quotes prices from the pricing tables, never typed', description: 'Staff quick replies and any price shown in chat come from packages / rates; the Figma "$50-$135" line is seed copy only.', category: 'account', status: 'in_dev', pages: ['C-82', 'F-61'], source: 'message-1.jpg' },
  { id: 'R-M11', title: 'Voice and video calls in chat', description: 'Figma front desk inbox draws call icons. Out of scope for launch: the app offers "Call the location" (tel: link) from Help instead.', category: 'account', status: 'requested', pages: ['C-77', 'F-61'], source: 'message-1.jpg' },
  { id: 'R-M20', title: 'One Front Desk thread per customer per location', description: 'The inbox lists one conversation per location (Encino, Westwood); the customer starts a thread from the inbox and a "Session start" marker opens it. Extends R-M09.', category: 'account', status: 'implemented', pages: ['C-81', 'C-82'], source: 'Message Support.png, notification-1.png, D-018', implementedIn: 'InboxPage.tsx' },
  { id: 'R-M21', title: 'Account deletion: 30-day grace, blocked by active bookings', description: 'Delete account writes account_deletion_requests (status requested, scheduled_for = today + 30), signs the customer out and can be cancelled by signing in again within 30 days. Customers with bookings in requested / pending_vaccines / confirmed / checked_in must cancel or complete them first.', category: 'account', status: 'implemented', pages: ['C-76'], source: 'setting.jpg, app-store requirement', implementedIn: 'DeleteAccountPage.tsx' },
  { id: 'R-M22', title: 'Saved cards are tokenised; only brand, last4 and expiry are stored', description: 'payment_methods stores the provider token (mock now, Stripe PaymentMethod later), never a card number or CVC. One default card per customer; removing the default promotes the next one.', category: 'account', status: 'implemented', pages: ['C-74'], source: 'Payment-1.png, Frame 1171276435.png', implementedIn: 'PaymentMethodsPage.tsx' },
  { id: 'R-M23', title: 'Notification preferences per category and channel', description: 'Bookings, vaccines, chat, payments and offers x push / email / SMS. Offers default off; bookings default on everywhere. Transactional legal notices (receipts, deletion) are always sent.', category: 'account', status: 'implemented', pages: ['C-75'], source: 'D-018, app-store requirement', implementedIn: 'NotificationPrefsPage.tsx' },
  { id: 'R-M24', title: 'Chat read receipts and delivery states', description: 'A customer message shows Sending -> Delivered -> Seen (messages.read set when staff open the thread); opening a thread marks staff messages read and zeroes conversations.unread_customer.', category: 'account', status: 'implemented', pages: ['C-82', 'F-61'], source: 'D-018 (chat best practices)', implementedIn: 'ChatThreadPage.tsx' },
  { id: 'R-M25', title: 'Chat bubbles follow the platform convention', description: 'The customer\'s own messages sit on the right in primary purple, Front Desk on the left in a neutral bubble (inverts the Figma draft, open question 66).', category: 'account', status: 'implemented', pages: ['C-82'], source: 'Message Support.png, D-018', implementedIn: 'ChatMessageBubble' },
  { id: 'R-M26', title: 'Languages offered: English and Spanish', description: 'The five Figma languages (English, Deutsch, French, Dutch, Bulgarian) are reduced to en + es until Justin confirms more; the choice is saved on the device and in users.preferred_language.', category: 'account', status: 'implemented', pages: ['C-73'], source: 'language.jpg, open question 63', implementedIn: 'LanguagePage.tsx' },
  { id: 'R-M27', title: 'Rate the app writes a pending review', description: 'Stars 1-5, tags Excellent / Amazing / Normal / Not good and a comment go to reviews (status pending) for the owner to moderate (R-M12); the store-review prompt follows once Capacitor is in.', category: 'account', status: 'implemented', pages: ['C-83', 'A-35'], source: 'profile.jpg (Rate App), reviews.jpg', implementedIn: 'RateAppPage.tsx' },
  { id: 'R-M28', title: 'Attachments in chat are images only, 2 MB max', description: 'Customers and staff can attach jpg / png / webp photos; uploads are mock data URLs until Company-OS storage exists.', category: 'account', status: 'in_dev', pages: ['C-82', 'F-61'], source: 'Message Support.png' },
]);
