import { defineRules } from './types';

/** Rules the customer hotel booking flow (C-30..C-41) adds. Ids R-X30..R-X39 are reserved for this module (append-only). */
export const rules = defineRules([
  { id: 'R-X30', title: 'Deposit is a settings percentage of the stay total', description: 'settings.hotel_booking.deposit_percent (seed 30 %) of the pre-fee total; the balance is due at check-in. Paying in full is the alternative (R-H02).', category: 'pricing', status: 'implemented', pages: ['C-35', 'C-36', 'C-39'], source: 'Booking Detail.jpg (Pay Deposit / Pay In Full); open question 47', implementedIn: 'src/modules/customer-hotel/lib.ts depositFor()' },
  { id: 'R-X31', title: 'App bookings start as requested, or pending vaccines', description: 'A stay booked in the app is `requested`; when any pet on it has a required vaccine that is not verified (missing, submitted, expired) it is `pending_vaccines` until staff verify (R-A05). The front desk confirms.', category: 'booking', status: 'implemented', pages: ['C-36', 'C-37', 'C-39'], source: 'Pet Edit 7.png, Home Page-1.png (Pending Verification)', implementedIn: 'src/modules/customer-hotel/lib.ts initialStatusFor()' },
  { id: 'R-X32', title: 'Customers request changes; staff approve', description: 'From the app a pet parent files a booking_change_requests row (modify dates, add / remove pet, add grooming, cancel). Only requested / pending_vaccines stays can be cancelled directly by the customer; confirmed stays need the desk (manager PIN, R-I06).', category: 'booking', status: 'implemented', pages: ['C-39', 'C-41'], source: 'D-003 (hotel consistency), D-019', implementedIn: 'booking_change_requests table' },
  { id: 'R-X33', title: 'Pets not sharing a room are separate rooms', description: 'share_room = yes quotes one room with N dogs (multi-dog discount applies, R-E01..E03); share_room = no quotes one room per pet at the single-dog rate.', category: 'pricing', status: 'implemented', pages: ['C-30', 'C-35'], source: 'Choose Pets-3.png; open question 39', implementedIn: 'src/modules/customer-hotel/lib.ts buildHotelQuote()' },
  { id: 'R-X34', title: 'Stay dates and times are validated', description: 'Check-out after check-in, at least settings.min_nights night(s), times inside the location opening hours for that weekday, no boarding-closed days.', category: 'booking', status: 'implemented', pages: ['C-30'], source: 'Choose Pets*.png, locations.hours (R-K02)', implementedIn: 'src/modules/customer-hotel/lib.ts validateStay()' },
  { id: 'R-X35', title: 'Grooming added to a stay is scheduled on check-out morning', description: 'One Grooming & Spa appointment per pet per stay, linked with appointments.booking_id, starting at 09:00 on the check-out day (R-A09: grooms happen at the end of stays; extra grooms via the front desk).', category: 'grooming', status: 'implemented', pages: ['C-33', 'C-35', 'C-36'], source: 'Booking Detail.jpg copy, Frame 1171276430.png', implementedIn: 'src/modules/customer-hotel/PaymentPage.tsx' },
  { id: 'R-X36', title: 'Room-type capacity blocks over-booking', description: 'Rooms needed for the dates are compared with capacities.max_simultaneous for the room type at the location minus overlapping active stays (requested, pending_vaccines, confirmed, checked_in). Full = the room card cannot be chosen.', category: 'capacity', status: 'implemented', pages: ['C-31'], source: 'R-E11, R-E12 (front desk-7.jpg)', implementedIn: 'src/modules/customer-hotel/lib.ts availability()' },
  { id: 'R-X37', title: 'Dogs 30 lb+ in a Penthouse need a bottom room', description: 'The app counts bottom penthouse rooms (rooms.position = bottom) free for the dates and warns / blocks when a 30 lb+ pet would not fit (R-E09). 55 lb+ pets can only book a Suite (R-X01).', category: 'room_fit', status: 'implemented', pages: ['C-31'], source: 'front desk-7.jpg note, D-006 seed rule', implementedIn: 'src/modules/customer-hotel/lib.ts roomFit()' },
  { id: 'R-X38', title: 'Card fee applies to the amount charged by card', description: 'The fees table card percent (3.89 %) is added to whatever is charged now by card: the deposit or the full amount. Cash at location carries no fee; the balance paid later by card is charged the fee at the desk.', category: 'fees_tax', status: 'implemented', pages: ['C-35', 'C-36'], source: 'Booking Detail-3.jpg footnote, R-H03', implementedIn: 'src/modules/customer-hotel/lib.ts chargeFor()' },
  { id: 'R-X39', title: 'Room card price is the average nightly rate for the chosen dates', description: '"Avg per night / pet" on the room cards = mean of the per-night rates (weekday / weekend / seasonal) over the selected stay, per pet, before discounts. Never a hardcoded number.', category: 'pricing', status: 'implemented', pages: ['C-31'], source: 'Choose Your Room.png ($150 / $105 / $115 conflict, open question 48)', implementedIn: 'src/pricing/engine.ts quoteHotel() per room type' },
]);
