import { defineRules } from './types';

const ENGINE = 'src/pricing/engine.ts';
const MOD = 'src/modules/customer-grooming-daycare';

/** Rules the customer Grooming & Spa and Daycare flows implement (C-50..C-69). Ids from docs/rules/business-rules-from-designs.md; R-X14.. are new owner rules. */
export const rules = defineRules([
  { id: 'R-G03', title: 'Gold Groom inclusions', description: 'Bath, blow-dry, brush teeth, four-paw massage and scented spray. Copy lives in packages.inclusions and is shown on the package card.', category: 'grooming', status: 'implemented', pages: ['C-50', 'C-51'], source: 'front desk-6.jpg, Spa 12.7 2.png', implementedIn: 'packages seed (inclusions)' },
  { id: 'R-G05', title: 'Platinum Groom inclusions', description: 'Gold package + nail trim, ear cleanse and gland expression.', category: 'grooming', status: 'implemented', pages: ['C-50', 'C-51'], source: 'front desk-6.jpg, Spa 12.7 2.png', implementedIn: 'packages seed (inclusions)' },
  { id: 'R-G08', title: 'Sanitary Trim add-on is a starting price', description: 'Trim under paws, private areas, between eyes; $10-20 depending on the dog, so the add-on is flagged starting_at and the quote footnotes it.', category: 'grooming', status: 'implemented', pages: ['C-52', 'C-54'], source: 'front desk-6.jpg, 12.pdf', implementedIn: 'addons seed + quoteGrooming notes' },
  { id: 'R-G13', title: 'Add-ons add calendar time by size', description: 'added_minutes_sm for S/M dogs, added_minutes_l for L/XL/Giant; the appointment duration and the slot picker use the sum.', category: 'grooming', status: 'implemented', pages: ['C-52', 'C-53'], source: 'front desk-6.jpg, 12.pdf', implementedIn: ENGINE },
  { id: 'R-G14', title: 'Mobile package example prices are placeholders', description: 'The $65 / $50 / $100 / $200 figures on the Figma grooming screens are template values; every price shown comes from the packages and addons tables for the pet\'s size.', category: 'grooming', status: 'deprecated', pages: ['C-51', 'C-52'], source: 'Frame 1171276428/29/35.png' },
  { id: 'R-G15', title: 'Grooming totals reconcile: package + add-ons + tax (+ card fee)', description: 'The Figma totals ($500 / $64 / $565) do not add up; the app computes subtotal, tax and fee with quoteGrooming and never types a total.', category: 'grooming', status: 'implemented', pages: ['C-54', 'C-55', 'C-56'], source: 'Frame 1171276434/35.png (error)', implementedIn: ENGINE },
  { id: 'R-G16', title: 'Several pets per Grooming & Spa order; past orders can be re-created', description: '"Groom another pet" adds a pet with its own package and add-ons to the same order (one time slot, one payment). "Re-create" loads a past order into a new draft and asks only for a new date and time.', category: 'grooming', status: 'implemented', pages: ['C-52', 'C-55', 'C-56'], source: 'Frame 1171276429/34.png', implementedIn: `${MOD}/draft.ts` },
  { id: 'R-G18', title: 'Recurring grooming appointments', description: 'Legacy: generated N months ahead, moved to the next working day on holidays. Not in the redesigned customer flow; the customer re-creates a past order instead.', category: 'grooming', status: 'requested', pages: ['C-56', 'F-33'], source: '8.pdf, image 169.png' },
  { id: 'R-G21', title: 'Grooming slots respect the per-location capacity', description: 'A time slot is offered only when, for every 15-minute step of the order, existing appointments plus the pets in the order stay within capacities.grooming (2 per location, R-E10). Choosing a specific groomer also requires that groomer to be free.', category: 'capacity', status: 'implemented', pages: ['C-53'], source: 'front desk-7.jpg', implementedIn: `${MOD}/slots.ts` },
  { id: 'R-F06', title: 'Daycare price is computed from the check-in / check-out times', description: 'The Figma mock showed "$45 for Half Day" for a 4 h day; the app derives hours from the two times and prices with quoteDaycare (half day under the threshold, full day at or above, play hour for one hour or less).', category: 'daycare', status: 'implemented', pages: ['C-61', 'C-63'], source: 'DayCare-1.png (error)', implementedIn: ENGINE },
  { id: 'R-A03', title: 'Daycare is bookable in the app (not "coming soon")', description: 'The "Daycare Service Coming Soon" placeholder is superseded by the full daycare flow (build plan C-60..C-69); the Coming Soon copy is not used.', category: 'daycare', status: 'implemented', pages: ['C-60'], source: 'Day care.png vs DayCare*.png (conflict; D-003)', implementedIn: `${MOD}/DaycareStartPage.tsx` },
  { id: 'R-A11', title: 'Vaccination status is shown while booking', description: 'Pet cards in the grooming and daycare flows show "Vaccines OK" or "Vaccines pending"; a booking with a pet whose required vaccines are not verified is created as pending_vaccines (R-A05).', category: 'vaccines', status: 'implemented', pages: ['C-51', 'C-61', 'C-54', 'C-63'], source: 'Board/Groom Booking .pdf ("Vaccination: OK")', implementedIn: `${MOD}/useCustomer.ts` },
  { id: 'R-X14', title: 'Customers cancel in the app only before confirmation', description: 'A grooming order or daycare day in requested / pending_vaccines can be cancelled by the pet parent in the app. Once confirmed, the app offers "Message the front desk" instead; staff changes go through the PIN-gated transitions (R-I06).', category: 'booking', status: 'implemented', pages: ['C-55', 'C-64'], source: 'build decision (customer-grooming-daycare pending decisions)', implementedIn: `${MOD}/GroomingOrderPage.tsx` },
  { id: 'R-X15', title: 'Grooming appointments fit inside location hours', description: 'Slots start at the location\'s opening time in 30-minute steps and the whole order (longest chair time) must end before closing; closed days and past times are not offered.', category: 'grooming', status: 'implemented', pages: ['C-53'], source: 'locations.hours (R-K02)', implementedIn: `${MOD}/slots.ts` },
  { id: 'R-X16', title: 'Daycare check-out is at least one hour after check-in and within hours', description: 'Times are offered in 15-minute steps between opening and closing; the check-out picker starts one hour after check-in. Closed days are disabled on the calendar.', category: 'daycare', status: 'implemented', pages: ['C-61'], source: 'DayCare-1.png, locations.hours', implementedIn: `${MOD}/DaycareBookPage.tsx` },
  { id: 'R-X17', title: 'Daycare day long enough for a groom offers "add grooming"', description: 'Implements R-X02: when the daycare day is at least the shortest package time plus a 60-minute buffer (setting daycare.grooming_buffer_min, default 60) the confirmation offers to book Grooming & Spa on the same day; shorter days show why not.', category: 'daycare', status: 'implemented', pages: ['C-61', 'C-64'], source: 'prompt 0002 (D-006), D-011', implementedIn: `${MOD}/DaycareBookPage.tsx` },
]);
