/**
 * Rules implemented or displayed by the customer home & pets module (C-10..C-29).
 * Ids from docs/rules/business-rules-from-designs.md where a design rule exists; R-X20..R-X29 are this module's
 * new rules (range reserved to avoid clashes with other modules' R-Xnn ids).
 */
import { defineRules } from './types';

export const rules = defineRules([
  { id: 'R-A04', title: 'Pets show an approval status to the customer', description: 'Approved / Pending verification / Needs more details (warning icon), derived from pets.approval_status and the vaccine records (R-X20).', category: 'vaccines', status: 'implemented', pages: ['C-10', 'C-11', 'C-13', 'C-20'], source: 'Home Page-1.png, Choose Vaccine.png', implementedIn: 'src/modules/customer-home-pets/lib.ts petApproval()' },
  { id: 'R-A06', title: 'Customers see "Pending verification" until the front desk verifies', description: 'Booking cards on the home use BOOKING_STATUS_CUSTOMER_LABEL: pending_vaccines -> Pending verification, confirmed -> Upcoming.', category: 'booking', status: 'implemented', pages: ['C-10'], source: 'Home Page-1.png', implementedIn: 'CustomerBookingCard + src/domain/booking.ts' },
  { id: 'R-C01', title: 'Required pet fields: name, type, sex, neutered / spayed', description: 'Breed, colour, weight and date of birth are optional. The wizard blocks Next until the required basics are filled.', category: 'people', status: 'implemented', pages: ['C-12', 'C-14'], source: 'Pet Edit.png, Frame 1171276417.png', implementedIn: 'PetWizardPage validateBasics()' },
  { id: 'R-C02', title: 'Weight is entered and shown in lbs', description: 'Numeric input with an lbs suffix (not a dropdown); the Kg on the UI-kit Pet Profile is not used. The size band (S/M/L/XL/Giant) is computed from the weight (R-X21).', category: 'people', status: 'implemented', pages: ['C-12', 'C-13', 'C-14'], source: 'Pet Edit.png vs Pet Profile (Single Pet).jpg', implementedIn: 'PetWizardPage step Size' },
  { id: 'R-C03', title: 'Socialisation is multi-select, personality single-select', description: 'Socialised with Humans / Dogs (checkboxes); personality Shy / Calm / Hyper / Aggressive (radio).', category: 'people', status: 'implemented', pages: ['C-12', 'C-14'], source: 'Pet Edit 3.png, Pet Edit-1.png', implementedIn: 'PetWizardPage step Care' },
  { id: 'R-C04', title: 'Meals per day are slot based', description: 'Options AM, PM, AM & PM, AM / Mid Day / PM, Free feeding (Figma "AM & PM" chosen over the numeric build variant); feeding instructions per slot.', category: 'people', status: 'implemented', pages: ['C-12', 'C-14'], source: 'Pet Edit 3.png vs Frame 1171276418.png', implementedIn: 'PET_MEALS in src/data/schema/customer-home-pets.ts' },
  { id: 'R-C05', title: 'Feeding instructions for AM, Mid Day and PM; own food and treats yes / no', description: 'Stored on pets.feeding_am / feeding_midday / feeding_pm, own_food, can_have_treats.', category: 'people', status: 'implemented', pages: ['C-12', 'C-13', 'C-14'], source: 'Pet Edit 3.png', implementedIn: 'pets table' },
  { id: 'R-B06', title: 'Vaccine proof accepts .jpg, .png and .pdf, several files over time', description: 'One proof per vaccine record; .gif is not accepted until confirmed (R-B05).', category: 'vaccines', status: 'implemented', pages: ['C-12', 'C-20', 'C-21'], source: 'Pet Edit 5.png', implementedIn: 'PetDocumentUpload accept' },
  { id: 'R-B08', title: 'Vet chosen from the list or added inline', description: 'Select from vets plus an "Add a vet" option that inserts a vets row.', category: 'people', status: 'implemented', pages: ['C-12', 'C-14'], source: 'Pet Edit 5.png, Pet Details .pdf', implementedIn: 'PetWizardPage step Vet & emergency' },
  { id: 'R-B09', title: 'Upload feedback shows file name, size and percent, and can be cancelled', description: 'Mock upload with a progress bar; a finished upload shows a green check, an in-progress one a red cancel.', category: 'vaccines', status: 'implemented', pages: ['C-12', 'C-20', 'C-21'], source: 'Pet Edit 7.png', implementedIn: 'PetDocumentUpload' },
  { id: 'R-M07', title: 'Customer notification kinds', description: 'pet_added, pet_approved, vaccine_verified, vaccine_expiring, vaccine_submitted (staff), booking_confirmed, payment, appointment_reminder, message. The UI-kit "order delivered" kinds are dropped.', category: 'account', status: 'implemented', pages: ['C-80'], source: 'notification.png', implementedIn: 'AppNotificationRow KIND_ICON' },
  { id: 'R-M08', title: 'Relative timestamps with correct grammar', description: '"Just now", "25 min ago", "3 hours ago", "Yesterday", "5 days ago", then the date.', category: 'account', status: 'implemented', pages: ['C-80', 'C-10'], source: 'notification.png', implementedIn: 'src/modules/customer-home-pets/lib.ts relativeTime()' },
  { id: 'R-X20', title: 'Per-vaccine status derives from the record and today', description: 'missing = no record or record.status missing / rejected; expired = expires_on before today (even when verified); pending = submitted, awaiting the front desk; verified otherwise. The pet chip shows the worst status among required vaccines.', category: 'vaccines', status: 'implemented', pages: ['C-10', 'C-11', 'C-13', 'C-20', 'C-21'], source: 'D-003, R-B11', implementedIn: 'src/modules/customer-home-pets/lib.ts vaccineStatusOf() / petVaccineSummary()' },
  { id: 'R-X21', title: 'Size band recomputed from weight on every pet save', description: 'S < 20 lb, M < 40, L < 70, XL < 100, Giant 100+ (working assumption, D-019). Grooming prices key off this band.', category: 'grooming', status: 'implemented', pages: ['C-12', 'C-14'], source: 'D-019', implementedIn: 'sizeFromWeightLbs() on save' },
  { id: 'R-X22', title: 'Emergency contact per pet', description: 'Name, phone and relationship, optional but prompted on the wizard; falls back to the household contact when a pet has none.', category: 'people', status: 'implemented', pages: ['C-12', 'C-13', 'C-14'], source: 'customer-home-pets decision', implementedIn: 'emergency_contacts table' },
  { id: 'R-X23', title: 'Customer picks a preferred location on the home', description: 'The picker sets the LocationProvider location (persisted per device) and customers.home_location_id; booking flows start at that location.', category: 'locations', status: 'implemented', pages: ['C-10'], source: 'project brief (two locations)', implementedIn: 'HomePage location picker' },
  { id: 'R-X24', title: 'Removing a pet is a soft delete and is blocked by upcoming bookings', description: 'pets.status -> inactive after a confirmation; refused when the pet is on a booking, appointment or daycare day that is not finished.', category: 'people', status: 'implemented', pages: ['C-13'], source: 'customer-home-pets decision', implementedIn: 'PetProfilePage removePet()' },
  { id: 'R-X25', title: 'New pets start pending; skipping vaccines marks them needs_details', description: 'Approval is granted by staff after verifying the required vaccines; the wizard tells the customer reservations stay pending until then (R-A05, R-B07).', category: 'vaccines', status: 'implemented', pages: ['C-12', 'C-20'], source: 'Pet Edit 7.png', implementedIn: 'PetWizardPage finish()' },
]);
