import { defineRules } from './types';

/**
 * Engineering rules the dev-quality pages enforce or report on. Ids R-X80..R-X89 are reserved for dev-quality so
 * they never collide with owner rules other modules add (R-X04+).
 */
export const rules = defineRules([
  { id: 'R-X80', title: 'No route without a spec; every spec reference must resolve', description: 'Every route carries a PageSpec. spec.data names tables that exist in the schema, spec.components names library components with a meta, spec.rules names registry ids. D-09 reports every unresolved reference and every missing field.', category: 'account', status: 'implemented', pages: ['D-03', 'D-09', 'D-19'], source: 'CLAUDE.md module contract', implementedIn: 'src/modules/dev-quality/specReport.ts' },
  { id: 'R-X81', title: 'No component without a meta, no meta without a usage and a11y notes', description: 'D-08 lists every component with its states, usages, a11y notes and the pages that use it; empty a11y or usage arrays are flagged.', category: 'account', status: 'implemented', pages: ['D-02', 'D-08'], source: 'CLAUDE.md components rule', implementedIn: 'src/modules/dev-quality/ComponentMatrixPage.tsx' },
  { id: 'R-X82', title: 'Every page works at 360, 390, 768, 1280 and 1920 px, light and dark (D-016)', description: 'scripts/qa-responsive.mjs loads every manifest route at the five widths in both themes and reports horizontal scroll and elements that overflow the viewport into docs/qa/responsive-report.md; D-12 shows the matrix. Timeline / board may degrade gracefully on phones.', category: 'account', status: 'implemented', pages: ['D-12', 'D-13'], source: 'D-016', implementedIn: 'scripts/qa-responsive.mjs' },
  { id: 'R-X83', title: 'Page layout edits persist per page code in page_layouts', description: 'The layout editor (D-11) reorders and hides the sections a spec declares; pages that call useLayout(spec) render in that order. One row per page code; the spec stays the source of section names.', category: 'account', status: 'implemented', pages: ['D-11'], source: 'hoy pattern (docs/reference/hoy-patterns.md)', implementedIn: 'src/layout/useLayout.ts' },
  { id: 'R-X84', title: 'Table edits are audited; deletes and bulk imports need a manager PIN', description: 'Inline edits in the data workbench (D-10) write audit_log rows; CSV import of more than one row and any delete open PinApprovalModal first (extends R-P01).', category: 'pin_approvals', status: 'implemented', pages: ['D-04', 'D-10'], source: 'R-P01, project brief', implementedIn: 'src/modules/dev-quality/DataWorkbenchPage.tsx' },
  { id: 'R-X85', title: 'Performance limits live in perf_budgets, not in code', description: 'D-16 compares bundle sizes (docs/qa/bundle-report.json) and runtime numbers against rows of perf_budgets; warn at warn_at_percent, fail above 100 %.', category: 'account', status: 'implemented', pages: ['D-16'], source: 'dev-quality module', implementedIn: 'src/data/seed/dev-quality.ts' },
  { id: 'R-X86', title: 'Demo data covers a full year so reports have history', description: 'The mock seed holds twelve months of hotel stays, grooming appointments and daycare days with invoices and payments, priced by the pricing engine from the settings tables; D-14 inspects it.', category: 'account', status: 'implemented', pages: ['D-14', 'A-01'], source: 'dev-quality scope', implementedIn: 'src/data/seed/dev-quality.ts' },
  { id: 'R-X87', title: 'Interactive elements have accessible names and images have alt text', description: 'D-15 scans a route in an iframe and lists buttons and links without a name, inputs without a label, images without alt, skipped heading levels and missing landmarks. The responsive QA script runs the same checks headless.', category: 'account', status: 'implemented', pages: ['D-15'], source: 'WCAG 2.2 AA (1.1.1, 1.3.1, 2.4.6, 4.1.2)', implementedIn: 'src/modules/dev-quality/a11yScan.ts' },
]);
