import { defineRules } from './types';

/** Rules the extras-manual-website module implements or registers: staff notifications and messages, reports, reviews on the website, the manual, education, walks and tasks. Ids append-only; R-X70+ are owner rules first registered here. */
export const rules = defineRules([
  { id: 'R-M07', title: 'Notification kinds are a fixed vocabulary', description: 'booking_confirmed, payment, vaccine_expiring, vaccine_submitted, pet_added, message, review, system. UI-kit leftovers from the design (orders, deliveries, vet reminders) are not kinds.', category: 'account', status: 'implemented', pages: ['F-60', 'C-80'], source: 'notification.png', implementedIn: 'F-60 kind filter + StaffNotificationRow icons' },
  { id: 'R-M08', title: 'Relative timestamps for notifications and conversations', description: '"5 min ago", "3 h ago", "Yesterday", "2 days ago"; older than a week shows the date.', category: 'account', status: 'implemented', pages: ['F-60', 'F-61', 'C-80'], source: 'notification.png, message-1.jpg', implementedIn: 'relativeTime() exported by StaffNotificationRow' },
  { id: 'R-M11', title: 'Front desk chat offers voice / video calls and attachments', description: 'Seen in the design; scope open. Images are supported on messages (image_url); calls are not planned.', category: 'operations', status: 'requested', pages: ['F-61'], source: 'message-1.jpg' },
  { id: 'R-M13', title: 'Email and SMS providers are configurable', description: 'Email None / Gmail / SMTP, SMS None / provider; test-send actions. Belongs to owner settings once notifications leave the mock.', category: 'account', status: 'requested', pages: ['A-40', 'F-60'], source: '5.pdf' },
  { id: 'R-L07', title: 'Employees have a check list; tasks are tracked per location', description: 'The Figma sidebar shows Tasks and Employees > Check List with no content. Tasks (F-68) hold both as kind task | checklist.', category: 'people', status: 'implemented', pages: ['F-68'], source: 'education-1.jpg, employees-1.jpg', implementedIn: 'tasks table (kind)' },
  { id: 'R-X70', title: 'Only published reviews appear on the public website', description: 'reviews.status must be published; pending and archived reviews never leave the moderation queue. Moderation (publish / archive) needs reviews.moderate.', category: 'operations', status: 'implemented', pages: ['P-07', 'F-65', 'A-35'], source: 'reviews.jpg + R-M12', implementedIn: 'P-07 filters status=published; F-65 ReviewListItem actions' },
  { id: 'R-X71', title: 'Website prices are teasers computed from the pricing tables', description: 'The public site shows "from" prices read from rates, packages, daycare_pricing, discounts, fees and taxes through the pricing engine; the binding quote is the one the app or the desk produces.', category: 'pricing', status: 'implemented', pages: ['P-02', 'P-03', 'P-04', 'P-05'], source: 'CLAUDE.md pricing rule', implementedIn: 'src/modules/extras-manual-website/site/teasers.ts' },
  { id: 'R-X72', title: 'Website inquiries are answered within one business day', description: 'Contact-form rows land as status new at the chosen location; the desk marks them seen / replied. Target: reply within one business day.', category: 'operations', status: 'requested', pages: ['P-10', 'F-61'], source: 'extras-manual-website decision (needs Justin)' },
  { id: 'R-X73', title: 'The ops manual never hardcodes a number the system owns', description: 'Prices, hours, capacities, statuses, roles and tables are rendered by LiveBlock directives ({{pricing:rooms}}, {{locations}}, ...) so chapters stay true when settings change.', category: 'operations', status: 'implemented', pages: ['M-01', 'M-10'], source: 'hoy ops-manual pattern (docs/reference/hoy-patterns.md section 6)', implementedIn: 'LiveBlock + manualIndex directives' },
  { id: 'R-X74', title: 'Training completion is tracked per employee per chapter', description: 'Each manual chapter is a lesson with an in-person and an online part; completing one writes a training_completions row (mode in_person | online). Managers sign off in-person lessons.', category: 'people', status: 'implemented', pages: ['F-66', 'M-01'], source: 'project brief (business operations manual)', implementedIn: 'training_completions table, F-66' },
  { id: 'R-X75', title: 'Walks are logged per pet with handler, start and duration', description: 'A walk row per outing; status planned -> in_progress -> done | skipped. The daycare "Walk" price item is billed from these rows later.', category: 'daycare', status: 'implemented', pages: ['F-67'], source: 'front desk-7.jpg (Walk $12), D-005 (walking extended later)', implementedIn: 'walks table, F-67' },
  { id: 'R-X76', title: 'Reports respect the location scope', description: 'Pinned roles see their location; owner and super admin switch or see all locations. Financial reports need reports.financial.', category: 'locations', status: 'implemented', pages: ['F-62', 'F-63', 'F-64'], source: 'project brief (location rules), R-L05', implementedIn: 'useLocation().scope + can(reports.financial)' },
  { id: 'R-X77', title: 'Deleting a task needs a manager PIN', description: 'Deleting records is approval-gated (R-P01); F-68 opens the PinApprovalModal before removing a task and writes the approval.', category: 'pin_approvals', status: 'implemented', pages: ['F-68'], source: 'R-P01', implementedIn: 'F-68 PinApprovalModal' },
  { id: 'R-X78', title: 'Staff notifications are per user and marked read on open', description: 'notifications.user_id is the signed-in staff user; opening the list marks visible rows read; the TopBar bell shows the unread count.', category: 'account', status: 'implemented', pages: ['F-60'], source: 'F-60 stub spec', implementedIn: 'F-60 markAllRead' },
]);
