/**
 * Rules implemented or displayed by the frontdesk-grooming-people module (F-30..F-59). Ids from
 * docs/rules/business-rules-from-designs.md; module-owned rules use R-X60..R-X69 (reserved for this module so the
 * parallel builders do not collide).
 */
import { defineRules } from './types';

export const rules = defineRules([
  { id: 'R-G20', title: 'Day-view appointment label: "Owner Last, PET; Breed; Package Size"', description: 'The legacy label format stays the accessible name and tooltip of every schedule card so groomers and screen readers read the same thing; the card itself shows pet + breed, customer and package chips. Flags are alert badges with text: vaccine issue, needs attention (unconfirmed / note), balance due.', category: 'grooming', status: 'implemented', pages: ['F-30', 'F-31'], source: 'Grooming.png', implementedIn: 'ScheduleCard' },
  { id: 'R-G16', title: 'Several pets per grooming order', description: 'The desk form accepts several pets for one visit; one appointment row is written per pet (same time, same groomer) so the day view and invoices stay per pet.', category: 'grooming', status: 'implemented', pages: ['F-33'], source: 'Groom Booking .pdf, Frame 1171276429.png', implementedIn: 'GroomBookingFormPage' },
  { id: 'R-G18', title: 'Recurring grooming bookings', description: 'Legacy supported every-N-weeks recurrence; the redesigned form does not show it. Not built until Justin confirms.', category: 'grooming', status: 'requested', pages: ['F-33'], source: '8.pdf, image 169.png' },
  { id: 'R-G21', title: 'Grooming capacity: max simultaneous appointments per location', description: 'capacities.kind = grooming (2 per location). The desk form warns when the chosen slot already has that many overlapping appointments; the day view shades over-capacity rows.', category: 'capacity', status: 'implemented', pages: ['F-30', 'F-33'], source: 'front desk-7.jpg', implementedIn: 'overlapCount() in module lib' },
  { id: 'R-A11', title: 'Vaccination status shown at booking time; expired vaccines flagged', description: 'Pet pickers and appointment cards show OK / pending / expired / missing computed from vaccine_records against the required vaccine types.', category: 'vaccines', status: 'implemented', pages: ['F-30', 'F-32', 'F-33', 'F-53', 'F-55'], source: 'Board/Groom Booking .pdf, all reservation grooming-2.jpg', implementedIn: 'petVaccineSummary()' },
  { id: 'R-A13', title: 'Pet attributes carry staff instructions', description: 'pets.attributes (Muzzle, Staff only...) show on the pet card, the groom form pet table and the day view tooltip.', category: 'people', status: 'implemented', pages: ['F-33', 'F-55'], source: 'image 114.png, Pet Details .pdf', implementedIn: 'PetDetailPage' },
  { id: 'R-B08', title: 'Vet chosen from a list or added inline', description: 'The pet form offers the vets table with a + to add a vet.', category: 'vaccines', status: 'implemented', pages: ['F-54'], source: 'Pet Edit 5.png, Pet Details .pdf', implementedIn: 'DeskLookupSelect' },
  { id: 'R-C06', title: 'Pet id is system-generated; breed can be Mixed; DOB can be approximate', description: 'Read-only id on the pet form; is_mixed and pet_profiles.dob_approximate checkboxes.', category: 'people', status: 'implemented', pages: ['F-54'], source: 'Pet Details .pdf', implementedIn: 'PetFormPage' },
  { id: 'R-J01', title: 'Customer required fields: city, state, mobile, email', description: 'Add Customer validates Town/City, State, Mobile and Email (first / last name too, since a nameless customer is useless).', category: 'people', status: 'implemented', pages: ['F-51'], source: 'Customer Details.pdf', implementedIn: 'CustomerFormPage' },
  { id: 'R-J04', title: 'Lookup lists are extendable inline via +', description: 'Breed, colour, city, reference, attributes, title and temper come from lookup_values; the + next to the select adds a value.', category: 'people', status: 'implemented', pages: ['F-51', 'F-54'], source: 'Customer/Pet Details .pdf', implementedIn: 'DeskLookupSelect + lookup_values' },
  { id: 'R-J05', title: 'New customer can be created inline from a booking form', description: 'Groom Bookings has a New Customer button that opens the customer form and returns to the booking with the new customer selected.', category: 'booking', status: 'implemented', pages: ['F-33', 'F-51'], source: 'Board/Groom Booking .pdf', implementedIn: 'GroomBookingFormPage (?return=)' },
  { id: 'R-J06', title: 'Notes can be printed on the invoice', description: 'appointment_extras.include_notes_on_invoice; the invoice sheet prints the note when set.', category: 'booking', status: 'implemented', pages: ['F-33', 'F-59'], source: 'Board/Groom Booking .pdf', implementedIn: 'DeskInvoiceSheet' },
  { id: 'R-J07', title: 'Customer defaults: Active, preferred contact mobile, customer since today, marketing on', description: 'Add Customer prefills these; the desk can change them.', category: 'people', status: 'implemented', pages: ['F-51'], source: 'image 115.png (legacy)', implementedIn: 'CustomerFormPage' },
  { id: 'R-J08', title: 'Audit trail on bookings and appointments', description: 'Every status change and PIN-gated edit writes an audit_log row (who, when, from -> to).', category: 'operations', status: 'implemented', pages: ['F-34', 'F-31', 'F-55'], source: 'image 165.png (legacy)', implementedIn: 'writeAudit() in module lib' },
  { id: 'R-I03', title: 'Detail pages show booking status and payment status side by side', description: 'Appointment detail: status badge (one vocabulary) plus payment status chip.', category: 'booking', status: 'implemented', pages: ['F-34'], source: 'front desk-5.jpg', implementedIn: 'AppointmentDetailPage' },
  { id: 'R-I11', title: 'Booking reminder flag (default on)', description: 'appointment_extras.reminder defaults to true; the notification job (later) uses it.', category: 'booking', status: 'implemented', pages: ['F-33'], source: 'Board/Groom Booking .pdf', implementedIn: 'appointment_extras' },
  { id: 'R-M08', title: 'Relative timestamps in inbox and notifications', description: '"5 min ago", "Yesterday", "3 days ago"; absolute date after a week.', category: 'operations', status: 'implemented', pages: ['F-57', 'F-60'], source: 'message-1.jpg, notification.png', implementedIn: 'relativeTime()' },
  { id: 'R-M11', title: 'Voice / video calls from the front desk chat', description: 'Icons in Figma; out of scope until a telephony provider is chosen (D-018 lets us drop them).', category: 'operations', status: 'requested', pages: ['F-57'], source: 'message-1.jpg' },
  { id: 'R-X60', title: 'Verifying every required vaccine approves the pet and confirms its pending bookings', description: 'When staff verify a record and all required vaccine_types for the pet are verified and unexpired, pets.approval_status becomes approved and every pending_vaccines hotel / daycare booking whose pets are all approved moves to confirmed (audit + customer notification).', category: 'vaccines', status: 'implemented', pages: ['F-55', 'F-56'], source: 'project brief (vaccines first-class), D-019', implementedIn: 'verifyVaccineRecord() in module lib' },
  { id: 'R-X61', title: 'Rejecting a vaccine proof asks for a reason and notifies the customer', description: 'status = rejected, note holds the reason; the pet stays pending and the customer gets a notification to re-upload.', category: 'vaccines', status: 'implemented', pages: ['F-55', 'F-56'], source: 'D-019', implementedIn: 'rejectVaccineRecord()' },
  { id: 'R-X62', title: 'Groomer columns: order, colour and hidden state are saved per staff user and location', description: 'groomer_column_prefs; the context menu on a column header writes them (open question 82 resolved: per user).', category: 'grooming', status: 'implemented', pages: ['F-30'], source: 'Grooming.png context menu', implementedIn: 'GroomDayGrid' },
  { id: 'R-X63', title: 'Appointment status changes follow the booking lifecycle rules', description: 'confirmed -> cancelled / no_show and re-opening a cancelled or no-show appointment need a manager PIN (mirrors PIN_GATED_TRANSITIONS); start / done by the desk do not.', category: 'pin_approvals', status: 'implemented', pages: ['F-31', 'F-34'], source: 'D-019, R-I06', implementedIn: 'appointmentNeedsPin()' },
  { id: 'R-X64', title: 'Discounts on a groom booking need a manager PIN', description: 'appointment_extras.discount_pct > 0 opens PinApprovalModal (action discount.apply) before the appointment is saved.', category: 'pin_approvals', status: 'implemented', pages: ['F-33'], source: 'R-P01', implementedIn: 'GroomBookingFormPage' },
  { id: 'R-X65', title: 'Desk-entered vaccine certificates are verified on entry', description: 'When a staff member with vaccines.verify enters dates and attaches a certificate on the pet form, the record is written as verified by them (they hold the paper); dates without a certificate are submitted; no dates = missing.', category: 'vaccines', status: 'implemented', pages: ['F-54'], source: 'Pet Details .pdf', implementedIn: 'PetFormPage' },
  { id: 'R-X66', title: 'Conversations can be assigned to a staff member', description: 'Inbox filter Mine / Unassigned / All; assignment stored in conversation_assignments.', category: 'operations', status: 'implemented', pages: ['F-57'], source: 'D-018 (improve messaging)', implementedIn: 'MessagesPage' },
  { id: 'R-X67', title: 'Invoices are numbered from settings.invoice.next_number', description: 'Creating an invoice from an appointment or booking reads and bumps settings.invoice.next_number (INV-####) and copies footer / title from the same setting.', category: 'operations', status: 'implemented', pages: ['F-59'], source: '9.pdf invoice settings', implementedIn: 'createInvoiceFor()' },
  { id: 'R-X68', title: 'Deleting a customer or pet needs a manager PIN and is a soft delete', description: 'record.delete approval; the row status becomes inactive rather than removed while bookings reference it.', category: 'pin_approvals', status: 'implemented', pages: ['F-52', 'F-55'], source: 'D-019 (deleting records is PIN-gated)', implementedIn: 'CustomerDetailPage / PetDetailPage' },
]);
