/**
 * Rules the front desk reservations module (F-01..F-29) implements or displays. Ids from
 * docs/rules/business-rules-from-designs.md; new ones are R-X03+ (append-only).
 */
import { defineRules } from './types';

export const rules = defineRules([
  { id: 'R-I02', title: 'Table status chips map onto the one lifecycle', description: 'Design chips Future / Checking In / Checked Out / Completed are rendered as confirmed / checked_in / checked_out through StatusBadge; no second vocabulary (R-I01, D-019).', category: 'booking', status: 'implemented', pages: ['F-01', 'F-10'], source: 'Frame 1171276264-10.png', implementedIn: 'StatusBadge + BOOKING_STATUS_LABEL' },
  { id: 'R-I07', title: 'Booking context actions: open, edit, set status, invoice, rebook', description: 'Timeline blocks and table rows offer Open, View/Edit, Set status (allowed transitions only, lock icon when PIN-gated), Create invoice and Rebook (prefilled new booking). Delete is PIN-gated (R-P01).', category: 'operations', status: 'implemented', pages: ['F-10', 'F-12', 'F-13'], source: 'all reservation grooming-3.jpg', implementedIn: 'BookingStatusMenu, RoomTimeline' },
  { id: 'R-I09', title: 'Status colour drives the timeline bar colour', description: 'Each stay block on the room timeline uses the booking status hue from tokens (R-I01).', category: 'booking', status: 'implemented', pages: ['F-13'], source: 'all reservation grooming.jpg (assumption)', implementedIn: 'RoomTimeline data-status' },
  { id: 'R-I11', title: 'Booking reminder flag', description: 'Desk bookings can carry a reminder flag (default on, as in the legacy system); it is stored in the booking quote metadata until a notifications job exists.', category: 'operations', status: 'in_dev', pages: ['F-11'], source: 'Board Booking.pdf' },
  { id: 'R-D13', title: 'Book out the whole hotel room', description: 'A desk booking can block a room for one party even when the room would fit more dogs; default from boarding settings.', category: 'operations', status: 'requested', pages: ['F-11'], source: '4.pdf, Board Booking.pdf' },
  { id: 'R-D16', title: 'Additional boarding services have an occurrence and M / A / E flags', description: 'booking_services rows: service, rate snapshot, qty, occurs once / daily / per night, morning / afternoon / evening.', category: 'operations', status: 'implemented', pages: ['F-11', 'F-12'], source: 'Board Booking.pdf, image 165.png', implementedIn: 'booking_services table' },
  { id: 'R-D17', title: 'Pickup / delivery (transport) can be required at a time', description: 'Transport fields on boarding and grooming bookings; deferred until the Walking / transport module exists.', category: 'operations', status: 'requested', pages: ['F-11'], source: 'Board/Groom Booking .pdf' },
  { id: 'R-J05', title: 'New customer can be created inline from a booking form', description: 'The New booking form opens a quick customer modal with the required fields (R-J01) and selects the new customer.', category: 'people', status: 'implemented', pages: ['F-11'], source: 'Board Booking.pdf', implementedIn: 'BookingFormPage quick customer' },
  { id: 'R-J06', title: 'Notes can be printed on the invoice', description: 'bookings.include_notes_on_invoice toggled on the booking form and detail.', category: 'operations', status: 'implemented', pages: ['F-11', 'F-12'], source: 'Board Booking.pdf', implementedIn: 'bookings.include_notes_on_invoice' },
  { id: 'R-J08', title: 'Audit trail on bookings', description: 'Every creation, status change, room move, date change, note and payment writes a booking_events row shown in the detail activity panel (legacy "Added ... by").', category: 'operations', status: 'implemented', pages: ['F-12'], source: 'image 165.png (legacy)', implementedIn: 'booking_events table' },
  { id: 'R-H08', title: 'Deposits tracked per booking; balance = total - deposits', description: 'Payments recorded at the desk update bookings.deposit; the table and detail show Total charge, Deposits, Balance (R-D14).', category: 'fees_tax', status: 'implemented', pages: ['F-10', 'F-12'], source: 'Board Booking.pdf, 9.pdf', implementedIn: 'BookingChargeSummary' },
  { id: 'R-E14', title: 'Hotel guests are not deducted from daycare capacity', description: 'Working answer to the designer question until Justin decides: daycare capacity counts daycare bookings only.', category: 'capacity', status: 'requested', pages: ['F-15'], source: 'front desk-7.jpg, 13.pdf (open question)' },
  { id: 'R-X03', title: 'Availability = active rooms of a type minus rooms occupied on any night of the range', description: 'Occupied = bookings in requested / pending_vaccines / confirmed / checked_in overlapping the night; unassigned bookings count against the type total. Checked-out, cancelled and no-show stays free the room.', category: 'capacity', status: 'implemented', pages: ['F-11', 'F-15', 'F-13'], source: 'D-019 (built fresh)', implementedIn: 'src/modules/frontdesk-reservations/lib/availability.ts' },
  { id: 'R-X04', title: 'A desk booking starts confirmed only when every required vaccine of every pet is verified', description: 'Otherwise it is created as pending_vaccines (R-A05); confirming it anyway needs a manager PIN (R-I06).', category: 'vaccines', status: 'implemented', pages: ['F-11', 'F-12'], source: 'D-019', implementedIn: 'lib/vaccines.ts petVaccineSummary' },
  { id: 'R-X05', title: 'Check-in requires a room; checked-in stays cannot change dates', description: 'Checking in without a room opens the room picker first; the room must fit the heaviest dog (R-E09).', category: 'booking', status: 'implemented', pages: ['F-12', 'F-13', 'F-01'], source: 'D-019 (built fresh)', implementedIn: 'useBookingActions' },
  { id: 'R-X06', title: 'Grooming board: cancelling or marking no-show an appointment needs a manager PIN', description: 'Dragging a card to Cancelled / No show on the Grooming & Spa board opens the PinApprovalModal; other columns move freely.', category: 'pin_approvals', status: 'implemented', pages: ['F-14'], source: 'R-I06 applied to appointments', implementedIn: 'BoardPage' },
  { id: 'R-X07', title: 'Moving a stay on the timeline keeps its length', description: 'Drag a block to another room or start day: nights stay the same, the room must be of the booked type and free for the new dates; the move is logged as a booking event.', category: 'operations', status: 'implemented', pages: ['F-13'], source: 'D-008 (timeline designed fresh)', implementedIn: 'RoomTimeline onBlockMove' },
]);
