import { defineRules } from './types';

export const rules = defineRules([
  { id: 'R-B01', title: 'Required vaccines: Rabies, DHPP (Distemper/Parvo), Bordetella', description: 'vaccine_types.required = true. A booking cannot be confirmed without a verified, unexpired record for each.', category: 'vaccines', status: 'implemented', pages: ['C-20', 'C-21', 'F-10'], source: 'Choose Vaccine.png, Pet Edit 5.png', implementedIn: 'vaccine_types seed' },
  { id: 'R-B02', title: 'Recommended vaccines: Leptospirosis, Canine Influenza', description: 'vaccine_types.required = false; shown but not blocking.', category: 'vaccines', status: 'implemented', pages: ['C-20', 'C-21'], source: 'Pet Edit 5.png', implementedIn: 'vaccine_types seed' },
  { id: 'R-B03', title: 'Each vaccine record has vaccinated date, expiry, reference and certificate', description: 'vaccine_records columns; status missing / submitted / verified / expired / rejected.', category: 'vaccines', status: 'implemented', pages: ['C-21', 'F-10'], source: 'Pet Details .pdf', implementedIn: 'vaccine_records table' },
  { id: 'R-B05', title: 'Accepted vaccine document formats .jpg .png .pdf', description: '.gif appears on one screen only; not accepted until confirmed.', category: 'vaccines', status: 'implemented', pages: ['C-21', 'C-12', 'C-20'], source: 'Choose Vaccine.png, Pet Edit 5.png' },
  { id: 'R-B07', title: 'Vaccine step is skippable at pet creation', description: 'The pet stays pending and bookings stay pending_vaccines.', category: 'vaccines', status: 'implemented', pages: ['C-20', 'C-12'], source: 'Pet Edit 5.png' },
  { id: 'R-B11', title: 'Expired vaccines are flagged on timeline, tables and pet cards', description: 'A record whose expires_on is past counts as expired even if verified.', category: 'vaccines', status: 'implemented', pages: ['F-01', 'F-12', 'C-10', 'C-20', 'F-55'], source: 'all reservation grooming-2.jpg' },
  { id: 'R-A12', title: 'Prompt about expired or missing compulsory vaccinations on pet and booking forms', description: 'Setting from the Control Panel.', category: 'vaccines', status: 'requested', pages: ['F-11', 'F-51'], source: '6.pdf' },
  { id: 'R-B10', title: 'Vaccination fee $40 is a chargeable extra service', description: 'services table category extra.', category: 'vaccines', status: 'implemented', pages: ['F-20'], source: 'Board Booking.pdf', implementedIn: 'services seed' },
]);
