import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'cgd.grooming': { en: 'Grooming & Spa', es: 'Peluquería y Spa' },
  'cgd.daycare': { en: 'Daycare', es: 'Guardería' },
  'cgd.bookNow': { en: 'Book now', es: 'Reservar' },
  'cgd.next': { en: 'Next', es: 'Siguiente' },
  'cgd.back': { en: 'Back', es: 'Atrás' },
  'cgd.choosePet': { en: 'Choose pet', es: 'Elige mascota' },
  'cgd.choosePackage': { en: 'Choose package', es: 'Elige paquete' },
  'cgd.addons': { en: 'Add-ons', es: 'Extras' },
  'cgd.groomAnother': { en: 'Groom another pet', es: 'Peluquear otra mascota' },
  'cgd.chooseTime': { en: 'Choose date & time', es: 'Elige fecha y hora' },
  'cgd.checkout': { en: 'Summary & payment', es: 'Resumen y pago' },
  'cgd.pastOrders': { en: 'Your Grooming & Spa orders', es: 'Tus reservas de Peluquería y Spa' },
  'cgd.recreate': { en: 'Re-create', es: 'Repetir' },
  'cgd.bookAgain': { en: 'Book again', es: 'Reservar de nuevo' },
  'cgd.selectPets': { en: 'Select your pets', es: 'Selecciona tus mascotas' },
  'cgd.dayTime': { en: 'Day & time', es: 'Día y hora' },
  'cgd.petDetails': { en: 'Additional pet details', es: 'Detalles adicionales' },
  'cgd.myDaycare': { en: 'Your daycare days', es: 'Tus días de guardería' },
  'cgd.payCard': { en: 'Credit / debit card', es: 'Tarjeta' },
  'cgd.payCash': { en: 'Pay at location', es: 'Pagar en el local' },
  'cgd.cancelBooking': { en: 'Cancel booking', es: 'Cancelar reserva' },
  'cgd.messageDesk': { en: 'Message the front desk', es: 'Escribir a recepción' },
};
