import { defineSpec } from '../../specs/defineSpec';

const SA = ['super_admin' as const];
export const tokensSpec = defineSpec({ code: 'D-01', name: 'Design tokens', purpose: 'Every design value in one place: brand palettes (Petrock purple, Sunset), neutrals, semantic roles per theme, type scale, spacing, radii, shadows, motion, booking status hues. Generated into tokens.css.', layout: ['PageHeader (theme + brand switch)', 'BrandPalettes', 'Neutrals', 'SemanticRoles', 'StatusHues', 'Typography', 'Spacing & radii', 'Shadows & motion'], data: [], roles: SA, logic: ['buildTokensCss() renders :root + [data-brand] x [data-theme] blocks; ThemeProvider sets the attributes.'], integrations: [], components: ['PageHeader', 'Section', 'Card', 'SegmentedControl', 'Badge'], rules: ['R-M04'], states: ['light', 'dark', 'petrock', 'sunset'], checkedAt: [360, 390, 768, 1280, 1920] });
export const componentsSpec = defineSpec({ code: 'D-02', name: 'Component library', purpose: 'Every component with its meta: description, props, states, live usages, accessibility notes, pages that use it and Figma source. Rule: no component without a meta.', layout: ['PageHeader', 'TierTabs', 'ComponentCards (props table, usages, a11y)'], data: [], roles: SA, logic: ['componentLibrary globs src/components/**/*.meta.ts.'], integrations: [], components: ['PageHeader', 'Tabs', 'Card', 'Badge', 'Chip', 'Section'], rules: [], states: ['by tier', 'anchor #Name'], checkedAt: [360, 390, 768, 1280, 1920] });
export const specsIndexSpec = defineSpec({ code: 'D-03', name: 'Page specs index', purpose: 'Every route with its page code, surface, built / stub status, roles and spec completeness; opens the inspector for any spec.', layout: ['PageHeader', 'StatTiles (built, stubs, avg completeness)', 'SurfaceFilter', 'SpecsTable', 'InspectorPanel'], data: [], roles: SA, logic: ['specCompleteness(spec) scores 8 checks.', 'status = PageStub element ? stub : built'], integrations: [], components: ['PageHeader', 'StatTile', 'DataTable', 'Badge', 'InspectorPanel', 'Chip'], rules: [], states: ['all', 'filtered by surface'], checkedAt: [360, 390, 768, 1280, 1920] });
export const tablesSpec = defineSpec({ code: 'D-04', name: 'Table library', purpose: 'Every table in the schema grouped by area with row counts, columns and access notes, plus the generic table manager that lists, adds, edits and deletes rows of any table (delete is PIN-gated).', layout: ['PageHeader', 'GroupSections (table cards)', 'TableManager (DataTable, row Drawer, PinApprovalModal)'], data: ['approvals', 'audit_log'], roles: SA, logic: ['tableRegistry from src/data/schema/*.ts', 'Base columns (id, location_id, created_at, updated_at) are read-only in the editor.', 'Delete asks for a manager PIN (R-P01) and writes approvals + audit_log.'], integrations: ['Company-OS /t/petrock/api/:entity (later)'], components: ['PageHeader', 'Card', 'DataTable', 'Drawer', 'Input', 'Select', 'Textarea', 'Checkbox', 'Button', 'PinApprovalModal', 'Badge', 'Tabs'], rules: ['R-J03', 'R-P01'], states: ['library', 'one table', 'editing row', 'delete approval'], checkedAt: [360, 390, 768, 1280, 1920] });
export const rulesSpec = defineSpec({ code: 'D-05', name: 'Business rules registry', purpose: 'Every business rule with id, category, status (requested / in dev / implemented / deprecated), the pages that use it and its source; owners add new rules here (Settings › Rules) and each page inspector links back.', layout: ['PageHeader (add rule)', 'StatusTiles', 'Filters (category, status, search)', 'RulesTable', 'AddRuleDrawer'], data: ['rules'], roles: ['owner', 'super_admin', 'manager'], logic: ['Code registry (src/rules/*.ts) merged with runtime rows from the rules table; runtime rows win on id.', 'Adding a rule needs rules.write.'], integrations: [], components: ['PageHeader', 'StatTile', 'DataTable', 'Badge', 'Drawer', 'Input', 'Select', 'Textarea', 'Button'], rules: [], states: ['all', 'filtered', 'adding'], checkedAt: [360, 390, 768, 1280, 1920] });
export const docsSpec = defineSpec({ code: 'D-06', name: 'Docs viewer', purpose: 'Renders every markdown file under docs/ in-app with a folder tree, images and screenshot galleries; prompt files split at "## Response".', layout: ['DocsSidebar (folder tree)', 'Document (MarkdownViewer)', 'ScreenshotGallery'], data: [], roles: ['super_admin', 'owner', 'manager'], logic: ['docsIndex globs docs/**/*.md (raw) and docs/screenshots + renders images (url).', 'Figma exports (69 MB) are not bundled; links to them stay as paths.'], integrations: [], components: ['MarkdownViewer', 'Figure', 'Section', 'Chip'], rules: [], states: ['index', 'document', 'prompt split', 'gallery'], checkedAt: [360, 390, 768, 1280, 1920] });
export const knowledgeSpec = defineSpec({ code: 'D-07', name: 'Knowledge base', purpose: 'Kanban, changelog (including pending module drafts) and prompt log in tabs; the project memory.', layout: ['PageHeader', 'Tabs (kanban, changelog, prompts, build plan)', 'Content'], data: [], roles: ['super_admin', 'owner'], logic: ['Changelog header lines (version, date, prompt, codes) are parsed by headerMeta().'], integrations: [], components: ['PageHeader', 'Tabs', 'MarkdownViewer', 'Card', 'Badge'], rules: [], states: ['kanban', 'changelog', 'prompts'], checkedAt: [360, 390, 768, 1280, 1920] });
