import type { StringTable } from '../../i18n/types';

export const strings: StringTable = {
  'customer-home-pets.home.greeting': { en: 'Hi {name}', es: 'Hola {name}' },
  'customer-home-pets.home.services': { en: 'Services', es: 'Servicios' },
  'customer-home-pets.home.pets': { en: 'Pets', es: 'Mascotas' },
  'customer-home-pets.home.upcoming': { en: 'Upcoming bookings', es: 'Próximas reservas' },
  'customer-home-pets.home.past': { en: 'View past bookings', es: 'Ver reservas pasadas' },
  'customer-home-pets.home.addPet': { en: 'Add a pet', es: 'Añadir mascota' },
  'customer-home-pets.home.addPetFirstTitle': { en: 'Add a pet first', es: 'Primero añade una mascota' },
  'customer-home-pets.home.addPetFirstBody': { en: 'To book a stay, grooming or daycare, please add your pet first. It takes about two minutes.', es: 'Para reservar hotel, peluquería o guardería, primero añade tu mascota. Tarda unos dos minutos.' },
  'customer-home-pets.home.location': { en: 'Location', es: 'Sede' },
  'customer-home-pets.home.chooseLocation': { en: 'Choose your Petrock', es: 'Elige tu Petrock' },
  'customer-home-pets.home.vaccineBanner': { en: 'Bookings stay pending until every required vaccine is verified by the front desk.', es: 'Las reservas quedan pendientes hasta que recepción verifique todas las vacunas obligatorias.' },
  'customer-home-pets.services.hotel': { en: 'Hotel', es: 'Hotel' },
  'customer-home-pets.services.grooming': { en: 'Grooming & Spa', es: 'Peluquería y Spa' },
  'customer-home-pets.services.daycare': { en: 'Daycare', es: 'Guardería' },
  'customer-home-pets.pets.title': { en: 'My pets', es: 'Mis mascotas' },
  'customer-home-pets.pets.empty': { en: 'No pets yet', es: 'Aún no hay mascotas' },
  'customer-home-pets.pets.emptyBody': { en: 'Add your dog to book the hotel, Grooming & Spa or daycare.', es: 'Añade tu perro para reservar hotel, peluquería o guardería.' },
  'customer-home-pets.wizard.add': { en: 'Add pet', es: 'Añadir mascota' },
  'customer-home-pets.wizard.edit': { en: 'Edit pet', es: 'Editar mascota' },
  'customer-home-pets.wizard.next': { en: 'Next', es: 'Siguiente' },
  'customer-home-pets.wizard.back': { en: 'Back', es: 'Atrás' },
  'customer-home-pets.wizard.save': { en: 'Save changes', es: 'Guardar cambios' },
  'customer-home-pets.wizard.submit': { en: 'Submit', es: 'Enviar' },
  'customer-home-pets.wizard.skip': { en: 'Skip for now', es: 'Omitir por ahora' },
  'customer-home-pets.wizard.pendingWarning': { en: 'Reservations will stay pending until your pet\'s required vaccines are uploaded and verified by the front desk.', es: 'Las reservas quedarán pendientes hasta que las vacunas obligatorias se suban y recepción las verifique.' },
  'customer-home-pets.vaccines.title': { en: 'Vaccines', es: 'Vacunas' },
  'customer-home-pets.vaccines.intro': { en: 'Choose your pet and upload the following vaccine information.', es: 'Elige tu mascota y sube la siguiente información de vacunas.' },
  'customer-home-pets.vaccines.required': { en: 'Required', es: 'Obligatorias' },
  'customer-home-pets.vaccines.recommended': { en: 'Recommended', es: 'Recomendadas' },
  'customer-home-pets.notifications.title': { en: 'Notifications', es: 'Notificaciones' },
  'customer-home-pets.notifications.markAll': { en: 'Mark all read', es: 'Marcar todo leído' },
  'customer-home-pets.notifications.empty': { en: 'You are all caught up', es: 'Estás al día' },
};
