import type { StringTable } from '../../i18n/types';

export const strings: StringTable = {
  'customer-home-pets.home.greeting': { en: 'Hi {name}', es: 'Hola {name}' },
  'customer-home-pets.home.services': { en: 'Services', es: 'Servicios' },
  'customer-home-pets.home.pets': { en: 'Pets', es: 'Mascotas' },
  'customer-home-pets.home.upcoming': { en: 'Upcoming Bookings', es: 'Próximas reservas' },
  'customer-home-pets.home.noUpcoming': { en: 'Nothing booked yet. Pick a service above to book a stay, a groom or a daycare day.', es: 'Aún no hay reservas. Elige un servicio arriba.' },
  'customer-home-pets.home.past': { en: 'View Past Reservations', es: 'Ver reservas pasadas' },
  'customer-home-pets.home.addPet': { en: 'Add a Pet', es: 'Añadir mascota' },
  'customer-home-pets.home.addPetFirstTitle': { en: 'Hey!', es: '¡Hola!' },
  'customer-home-pets.home.addPetFirstBody': { en: 'To Book An Appointment Please 1st Add A Pet', es: 'Para reservar, primero añade una mascota' },
  'customer-home-pets.home.location': { en: 'Location', es: 'Sede' },
  'customer-home-pets.home.chooseLocation': { en: 'Choose your Petrock', es: 'Elige tu Petrock' },
  'customer-home-pets.home.vaccineBanner': { en: 'Bookings stay pending until every required vaccine is verified by the front desk.', es: 'Las reservas quedan pendientes hasta que recepción verifique todas las vacunas obligatorias.' },
  'customer-home-pets.services.hotel': { en: 'Hotel', es: 'Hotel' },
  'customer-home-pets.services.grooming': { en: 'Grooming & Spa', es: 'Peluquería y Spa' },
  'customer-home-pets.services.spa': { en: 'Spa', es: 'Spa' },
  'customer-home-pets.services.inhome': { en: 'In Home', es: 'A domicilio' },
  'customer-home-pets.services.inhomeSoon': { en: 'In Home service coming soon', es: 'Servicio a domicilio próximamente' },
  'customer-home-pets.services.inhomeBody': { en: 'Ask the front desk in chat about in-home visits.', es: 'Pregunta a recepción por chat sobre visitas a domicilio.' },
  'customer-home-pets.services.daycare': { en: 'Daycare', es: 'Guardería' },
  'customer-home-pets.pets.title': { en: 'My Pets', es: 'Mis mascotas' },
  'customer-home-pets.pets.empty': { en: 'No pets yet', es: 'Aún no hay mascotas' },
  'customer-home-pets.pets.emptyBody': { en: 'Add your dog to book the hotel, Grooming & Spa or daycare.', es: 'Añade tu perro para reservar hotel, peluquería o guardería.' },
  'customer-home-pets.wizard.add': { en: 'Add Pet', es: 'Añadir mascota' },
  'customer-home-pets.wizard.edit': { en: 'Edit Pet', es: 'Editar mascota' },
  'customer-home-pets.wizard.next': { en: 'Next', es: 'Siguiente' },
  'customer-home-pets.wizard.back': { en: 'Back', es: 'Atrás' },
  'customer-home-pets.wizard.save': { en: 'Save changes', es: 'Guardar cambios' },
  'customer-home-pets.wizard.submit': { en: 'Submit', es: 'Enviar' },
  'customer-home-pets.wizard.skip': { en: 'Skip for now', es: 'Omitir por ahora' },
  'customer-home-pets.wizard.pendingWarning': { en: 'Reservations will stay pending until your pet\'s required vaccines are uploaded and verified by the front desk.', es: 'Las reservas quedarán pendientes hasta que las vacunas obligatorias se suban y recepción las verifique.' },
  'customer-home-pets.vaccines.title': { en: 'Vaccines', es: 'Vacunas' },
  'customer-home-pets.vaccines.intro': { en: 'Choose your pet and upload the following vaccine information.', es: 'Elige tu mascota y sube la siguiente información de vacunas.' },
  'customer-home-pets.vaccines.required': { en: 'Required', es: 'Obligatorias' },
  'customer-home-pets.vaccines.recommended': { en: 'Recommended', es: 'Recomendadas' },
  'customer-home-pets.notifications.title': { en: 'Notifications', es: 'Notificaciones' },
  'customer-home-pets.notifications.markAll': { en: 'Mark all read', es: 'Marcar todo leído' },
  'customer-home-pets.notifications.empty': { en: 'You are all caught up', es: 'Estás al día' },
};
