/**
 * Placeholder homes so every ROLE_HOME and shell link resolves before the modules ship. The registry prefers a real
 * (non-PageStub) route at the same path, so module agents simply register theirs; nobody edits this file.
 */
import { createElement as h } from 'react';
import type { RouteDef } from '../../specs/types';
import { defineSpec } from '../../specs/defineSpec';
import { PageStub } from '../../components/template/PageStub/PageStub';
import { ALL_SIGNED_IN, EVERYONE, STAFF_ROLES } from '../../auth/roles';

export const strings = {};
const stub = (r: Omit<RouteDef, 'element'>): RouteDef => ({ ...r, element: h(PageStub, { spec: r.spec }) });

export const routes: RouteDef[] = [
  stub({ path: '/app', roles: ['customer', 'super_admin'], surface: 'customer', layout: 'mobile', nav: { label: 'Home', icon: 'home', order: 0, group: 'customer' }, spec: defineSpec({ code: 'C-10', name: 'Customer home', purpose: 'Pet parent home: pets with approval status, upcoming bookings, service tiles (Hotel, Daycare, Grooming & Spa, In Home via chat).', layout: ['Header (location, bell)', 'PetsStrip', 'ServiceTiles', 'UpcomingBookings'], data: ['pets', 'bookings', 'appointments', 'daycare_bookings', 'notifications'], roles: ['customer'], logic: ['R-A01 add a pet before booking'], integrations: [], components: ['Avatar', 'Badge', 'Card', 'BottomNav'], rules: ['R-A01', 'R-A02', 'R-A04'], figma: ['Home Page-1.png'] }) }),
  stub({ path: '/auth/sign-in', roles: EVERYONE, surface: 'customer', layout: 'mobile', spec: defineSpec({ code: 'C-02', name: 'Sign in', purpose: 'Customer sign in (email + password, remember me, forgot password) - D-018 allows improving beyond Figma.', layout: ['Brand', 'Form', 'Links'], data: ['users', 'customers'], roles: EVERYONE, logic: [], integrations: ['Company-OS auth (later)'], components: ['Input', 'Button', 'Checkbox'], rules: ['R-M14'], figma: ['Frame 1171276422.png'] }) }),
  stub({ path: '/desk', roles: STAFF_ROLES, surface: 'frontdesk', layout: 'desktop', nav: { label: 'Today', icon: 'home', order: 0, group: 'overview' }, spec: defineSpec({ code: 'F-01', name: 'Front desk today', purpose: 'Run the day at one location: KPIs, arrivals / departures / staying / checked out tabs, reservations table with status changes (PIN-gated).', layout: ['PageHeader', 'StatTiles', 'DayTabs', 'ReservationsTable'], data: ['bookings', 'booking_pets', 'customers', 'pets', 'rooms', 'capacities'], roles: STAFF_ROLES, logic: ['dayBucket()', 'transitionNeedsPin()'], integrations: [], components: ['StatTile', 'Tabs', 'DataTable', 'StatusBadge', 'PinApprovalModal'], rules: ['R-I05', 'R-I06', 'R-I01'], figma: ['front desk-4.jpg', 'Frame 1171276264.png'] }) }),
  stub({ path: '/desk/grooming', roles: STAFF_ROLES, surface: 'frontdesk', layout: 'desktop', nav: { label: 'Day view', icon: 'scissors', order: 0, group: 'grooming' }, spec: defineSpec({ code: 'F-30', name: 'Grooming day view', purpose: 'Groomer columns with appointments by time; drag to reschedule; board view by status.', layout: ['PageHeader', 'DateStrip', 'GroomerColumns'], data: ['appointments', 'employees', 'pets', 'packages', 'addons'], roles: STAFF_ROLES, logic: ['duration from package + add-on minutes'], integrations: [], components: ['SegmentedControl', 'Badge', 'Avatar'], rules: ['R-G10', 'R-G17', 'R-E10'], figma: ['Grooming.png'] }) }),
  stub({ path: '/desk/notifications', roles: STAFF_ROLES, surface: 'frontdesk', layout: 'desktop', spec: defineSpec({ code: 'F-60', name: 'Staff notifications', purpose: 'Notifications for the signed-in staff user (vaccine proofs submitted, new app bookings, messages).', layout: ['PageHeader', 'NotificationList'], data: ['notifications'], roles: STAFF_ROLES, logic: ['mark read on open'], integrations: [], components: ['Card', 'Badge', 'EmptyState'], rules: ['R-M07'] }) }),
  stub({ path: '/admin', roles: ['owner', 'super_admin'], surface: 'admin', layout: 'desktop', nav: { label: 'Dashboard', icon: 'chart', order: 0, group: 'overview' }, spec: defineSpec({ code: 'A-01', name: 'Owner dashboard', purpose: 'KPIs across locations: revenue, occupancy, arrivals, grooming, pending vaccines, feedback.', layout: ['PageHeader', 'StatTiles', 'RevenueChart', 'LocationCompare'], data: ['bookings', 'appointments', 'daycare_bookings', 'invoices', 'payments', 'feedback'], roles: ['owner', 'super_admin'], logic: ['sum totals by location and period'], integrations: [], components: ['StatTile', 'Card', 'Tabs'], rules: ['R-K01'], figma: ['front desk-3.jpg'] }) }),
  stub({ path: '/manual', roles: ALL_SIGNED_IN, surface: 'manual', layout: 'desktop', nav: { label: 'Manual home', icon: 'book', order: 0, group: 'manual' }, spec: defineSpec({ code: 'M-01', name: 'Ops manual cover', purpose: 'Business operations manual: who reads what per role, chapters with screenshots and live data blocks.', layout: ['Cover', 'RoleMatrix', 'ChapterGrid'], data: ['locations', 'rules'], roles: ALL_SIGNED_IN, logic: ['chapters from docs/ops-manual/*.md at build time'], integrations: [], components: ['Card', 'Figure', 'MarkdownViewer'], rules: [] }) }),
];
