import type { StringTable } from '../../i18n/types';

export const strings: StringTable = {
  'customer-auth.brand': { en: 'Petrock Hotel and Spa', es: 'Petrock Hotel y Spa' },
  'customer-auth.newTo': { en: 'New to Petrock?', es: '¿Nuevo en Petrock?' },
  'customer-auth.createAccount': { en: 'Create account', es: 'Crear cuenta' },
  'customer-auth.haveAccount': { en: 'Already have an account?', es: '¿Ya tienes cuenta?' },
  'customer-auth.signIn': { en: 'Sign in', es: 'Iniciar sesión' },
  'customer-auth.signOut': { en: 'Sign out', es: 'Cerrar sesión' },
  'customer-auth.continueAs': { en: 'Continue as {name}', es: 'Continuar como {name}' },
  'customer-auth.staffSignIn': { en: 'Staff? Sign in with your PIN', es: '¿Personal? Entra con tu PIN' },
  'customer-auth.howItWorks': { en: 'How Petrock works', es: 'Cómo funciona Petrock' },
  'customer-auth.welcomeBack': { en: 'Welcome back', es: 'Bienvenido de nuevo' },
  'customer-auth.signInSubtitle': { en: 'Sign in to book, manage your dogs and chat with the front desk.', es: 'Inicia sesión para reservar, gestionar tus perros y chatear con recepción.' },
  'customer-auth.createTitle': { en: 'Create your account', es: 'Crea tu cuenta' },
  'customer-auth.createSubtitle': { en: 'One account for both locations, all your dogs and every booking.', es: 'Una cuenta para ambas sedes, todos tus perros y cada reserva.' },
  'customer-auth.firstName': { en: 'First name', es: 'Nombre' },
  'customer-auth.lastName': { en: 'Last name', es: 'Apellido' },
  'customer-auth.email': { en: 'Email', es: 'Correo electrónico' },
  'customer-auth.mobile': { en: 'Mobile (optional)', es: 'Móvil (opcional)' },
  'customer-auth.homeLocation': { en: 'Your usual Petrock', es: 'Tu Petrock habitual' },
  'customer-auth.password': { en: 'Password', es: 'Contraseña' },
  'customer-auth.newPassword': { en: 'New password', es: 'Nueva contraseña' },
  'customer-auth.rememberMe': { en: 'Remember me for 30 days', es: 'Recordarme 30 días' },
  'customer-auth.forgot': { en: 'Forgot password?', es: '¿Olvidaste tu contraseña?' },
  'customer-auth.forgotTitle': { en: 'Forgot your password?', es: '¿Olvidaste tu contraseña?' },
  'customer-auth.forgotBody': { en: 'Enter the email you signed up with and we will send a 6-digit code to reset it.', es: 'Escribe el correo con el que te registraste y te enviaremos un código de 6 dígitos.' },
  'customer-auth.sendCode': { en: 'Send code', es: 'Enviar código' },
  'customer-auth.resetTitle': { en: 'Set a new password', es: 'Elige una nueva contraseña' },
  'customer-auth.resetBody': { en: 'Enter the code we emailed you and choose a new password.', es: 'Introduce el código que te enviamos y elige una nueva contraseña.' },
  'customer-auth.updatePassword': { en: 'Update password', es: 'Actualizar contraseña' },
  'customer-auth.verifyTitle': { en: 'Check your email', es: 'Revisa tu correo' },
  'customer-auth.verifyEmail': { en: 'Verify your email', es: 'Verifica tu correo' },
  'customer-auth.verifyLater': { en: 'Skip for now', es: 'Omitir por ahora' },
  'customer-auth.lockedTitle': { en: 'Too many attempts', es: 'Demasiados intentos' },
  'customer-auth.lockedBody': { en: 'To protect your account we paused sign-in for a little while. You can reset your password right away, or try again when the timer ends.', es: 'Para proteger tu cuenta pausamos el inicio de sesión un momento. Puedes restablecer tu contraseña ahora o intentarlo cuando termine el temporizador.' },
  'customer-auth.tryAgainIn': { en: 'Try again in', es: 'Intenta de nuevo en' },
  'customer-auth.tryAgain': { en: 'Try again', es: 'Intentar de nuevo' },
  'customer-auth.resetPassword': { en: 'Reset password', es: 'Restablecer contraseña' },
  'customer-auth.contactDesk': { en: 'Call the front desk', es: 'Llama a recepción' },
  'customer-auth.welcomeTitle': { en: "You're in, {name}!", es: '¡Listo, {name}!' },
  'customer-auth.welcomeBody': { en: 'Your account is ready. Three quick steps and your dog can check in.', es: 'Tu cuenta está lista. Tres pasos rápidos y tu perro podrá registrarse.' },
  'customer-auth.goHome': { en: 'Go to my Petrock', es: 'Ir a mi Petrock' },
  'customer-auth.terms': { en: 'I agree to the Terms of Service and Privacy Policy', es: 'Acepto los Términos del servicio y la Política de privacidad' },
  'customer-auth.marketing': { en: 'Send me offers and Petrock news (optional)', es: 'Enviarme ofertas y novedades de Petrock (opcional)' },
  'customer-auth.signOutTitle': { en: 'Sign out of Petrock?', es: '¿Cerrar sesión en Petrock?' },
  'customer-auth.signOutBody': { en: 'Your bookings and dogs stay safe. Sign back in any time.', es: 'Tus reservas y perros quedan a salvo. Vuelve a entrar cuando quieras.' },
  'customer-auth.signedOut': { en: "You're signed out", es: 'Has cerrado sesión' },
  'customer-auth.back': { en: 'Back', es: 'Volver' },
  'customer-auth.demoHint': { en: 'Demo', es: 'Demo' },
};
