import { defineSpec } from '../../specs/defineSpec';
import type { PageSpec } from '../../specs/types';
import { EVERYONE, STAFF_ROLES, type Role } from '../../auth/roles';
import { liveDirectiveTables } from '../../components/organism/LiveBlock/LiveBlock';
import type { ManualChapter } from './manual/manualIndex';

const W = [360, 390, 768, 1280, 1920];
const MGMT: Role[] = ['super_admin', 'owner', 'manager'];
const SITE = ['SiteLayout', 'SiteHero', 'Button', 'Card', 'Icon'];
const siteSpec = (s: Omit<PageSpec, 'roles' | 'checkedAt' | 'integrations'> & { integrations?: string[] }): PageSpec => defineSpec({ ...s, roles: EVERYONE, integrations: s.integrations ?? ['Squarespace (current petrockhotel.com, to be replaced by these pages)', 'Customer app deep links (/app, /auth/sign-in)'], checkedAt: W });

// ---- Public website P-01..P-12 ----
export const siteHomeSpec = siteSpec({ code: 'P-01', name: 'Website home', purpose: 'Petrock brand landing: hero with tagline, the three services with live "from" teasers, why Petrock, both locations with hours and open-now, published reviews with the average rating, how it works, book-now CTA into the app.', layout: ['SiteLayout header', 'SiteHero (tagline, open-now card)', 'Services (Hotel, Daycare, Grooming & Spa tiles with teasers)', 'Why Petrock', 'Locations strip', 'Reviews (published)', 'How it works', 'CtaBand', 'Footer'], data: ['locations', 'room_types', 'rates', 'packages', 'daycare_pricing', 'reviews', 'customers'], logic: ['Teasers = min standard-season nightly rate per room type, Gold price_s, full-day daycare price (R-X71).', 'Open now = current time inside locations.hours for today.', 'Only reviews with status published are shown (R-X70); customer shown as first name + initial.'], components: [...SITE, 'Badge', 'ReviewListItem', 'ReviewStars'], rules: ['R-X70', 'R-X71', 'R-K02', 'R-A01'], states: ['default', 'no published reviews', 'closed now', 'dark'], figma: ['front desk.jpg (brand)', 'Home Page-1.png (service tiles)'] });
export const siteHotelSpec = siteSpec({ code: 'P-02', name: 'Website: Hotel', purpose: 'Room types with description, inclusions and "from" nightly rate (weekday and weekend), shared-room and long-stay discounts read from discounts, seasons, vaccines required before a stay.', layout: ['SiteHero (soft)', 'RoomType blocks (Art + inclusions + from price)', 'Good to know (sharing, longer stays, vaccines)', 'CtaBand'], data: ['room_types', 'rates', 'seasons', 'discounts', 'capacities', 'locations', 'vaccine_types'], logic: ['from = min(rates where season_id null) per room type; weekend rate shown when present.', 'Room count = sum of penthouse + suite capacities across locations.'], components: [...SITE, 'Badge'], rules: ['R-D01', 'R-D05', 'R-D06', 'R-E01', 'R-X71'], states: ['default', 'dark'], figma: ['Choose Your Room.png'] });
export const siteGroomingSpec = siteSpec({ code: 'P-03', name: 'Website: Grooming & Spa', purpose: 'One service: Gold / Platinum / Diamond tiles with inclusions, full package-by-size price table, add-ons with minutes, hotel-guest note, CTA.', layout: ['SiteHero (soft)', 'Package tiles', 'Price table by size', 'Add-ons grid', 'Hotel guests', 'CtaBand'], data: ['packages', 'addons'], logic: ['Prices per size column from packages.price_* (S/M/L/XL/Giant); minutes range minutes_s–minutes_giant.', 'Add-on "from" when starting_at.'], components: [...SITE, 'Badge'], rules: ['R-G02', 'R-G04', 'R-G06', 'R-X71'], states: ['default', 'dark'], figma: ['Spa 12.7 price card', 'Grooming.png'] });
export const siteDaycareSpec = siteSpec({ code: 'P-04', name: 'Website: Daycare', purpose: 'Daycare price items with thresholds, extra-pet discount, a typical day, capacity per location, CTA.', layout: ['SiteHero (soft)', 'Price tiles', 'A typical day (steps)', 'Capacity per location', 'CtaBand'], data: ['daycare_pricing', 'discounts', 'capacities', 'locations'], logic: ['Half day / full day copy uses daycare_pricing.threshold_hours (R-F01), never a typed number.'], components: [...SITE], rules: ['R-F01', 'R-F02', 'R-E13', 'R-X71'], states: ['default', 'dark'], figma: ['Day Care.png (placeholder screen)'] });
export const sitePricingSpec = siteSpec({ code: 'P-05', name: 'Website: Pricing', purpose: 'Pricing teaser page: every price live from the tables: room rates by day kind and season, discounts, Grooming & Spa by size, add-ons, daycare items, fees and taxes, how a quote adds up.', layout: ['SiteHero (soft)', 'Hotel rates table', 'Discount cards', 'Grooming table + add-ons table', 'Daycare table', 'Fees & taxes cards', 'Example', 'CtaBand'], data: ['room_types', 'rates', 'seasons', 'discounts', 'packages', 'addons', 'daycare_pricing', 'fees', 'taxes'], logic: ['Tables render rows verbatim; the binding quote is the pricing engine in the app (R-X71).'], components: [...SITE, 'Section'], rules: ['R-D05', 'R-D06', 'R-E01', 'R-E05', 'R-H03', 'R-H04', 'R-G02', 'R-F01', 'R-X71'], states: ['default', 'dark'], figma: ['front desk-7.jpg (settings prices)', '13.pdf'] });
export const siteLocationsSpec = siteSpec({ code: 'P-06', name: 'Website: Locations', purpose: 'Each location with address, phone, weekly hours collapsed into ranges, open-now badge, capacities, directions link, map placeholder and message-this-location link.', layout: ['SiteHero (soft)', 'Per location: card + map placeholder', 'Arriving', 'CtaBand'], data: ['locations', 'capacities'], logic: ['hoursSummary() collapses identical consecutive days (Mon–Fri, Sat–Sun).', 'isOpenNow() from locations.hours and the browser clock.'], components: [...SITE, 'Badge'], rules: ['R-K01', 'R-K02', 'R-E11', 'R-E12', 'R-E13'], states: ['open', 'closed', 'dark'], figma: ['1.pdf (locations)'] });
export const siteReviewsSpec = siteSpec({ code: 'P-07', name: 'Website: Reviews', purpose: 'All published reviews with location filter, average rating and star distribution; pending and archived never appear.', layout: ['SiteHero (soft)', 'Location filter + list', 'Average + distribution card', 'CtaBand (rate in app)'], data: ['reviews', 'customers', 'locations'], logic: ['where status = published (R-X70); average and distribution computed client-side.'], components: [...SITE, 'SegmentedControl', 'ReviewListItem', 'ReviewStars', 'EmptyState'], rules: ['R-X70', 'R-M12'], states: ['reviews', 'empty', 'dark'], figma: ['reviews.jpg (moderation source)'] });
export const sitePoliciesSpec = siteSpec({ code: 'P-08', name: 'Website: Vaccines & policies', purpose: 'Required and recommended vaccines from vaccine_types, how verification works, what each booking status means to a parent, deposit / card fee / prepay / cancellation notes.', layout: ['SiteHero (soft)', 'Vaccines list', 'Booking statuses (customer labels)', 'Payments & changes cards', 'CtaBand'], data: ['vaccine_types', 'fees', 'discounts'], logic: ['StatusBadge with customer labels for the one lifecycle.', 'Card fee percent from fees; prepay copy from discounts requiring paid_in_full.'], components: [...SITE, 'Badge', 'StatusBadge'], rules: ['R-A05', 'R-B01', 'R-H03', 'R-E05'], states: ['default', 'dark'], figma: ['Pet Edit 7.png (pending until vaccine copy)'] });
export const siteBookSpec = siteSpec({ code: 'P-09', name: 'Website: Book now', purpose: 'Hand-off into the customer app: choose hotel / daycare / grooming, what to have ready, sign-in link.', layout: ['SiteHero (brand, centered)', 'Service choice cards', 'Have these ready (steps)', 'Sign in / call links'], data: ['locations'], logic: ['All three choices deep-link to /app (the customer surface picks the flow); existing accounts go to /auth/sign-in.'], components: [...SITE], rules: ['R-A01', 'R-A05'], states: ['default', 'dark'] });
export const siteContactSpec = siteSpec({ code: 'P-10', name: 'Website: Contact', purpose: 'Phones and addresses per location and a contact form that writes a site_inquiries row for the chosen location; the desk handles it in F-61.', layout: ['SiteHero (soft)', 'Form card (location, name, email, phone, topic, message)', 'Location cards + app note'], data: ['locations', 'site_inquiries'], logic: ['Validation: name, email pattern, message >= 10 chars.', 'insert site_inquiries { status new, location_id } (R-X72); ?location= preselects.'], components: [...SITE, 'Input', 'Select', 'Textarea', 'EmptyState', 'Toast'], rules: ['R-X72', 'R-A02'], states: ['form', 'sent', 'dark'], integrations: ['Email / SMS notification to the desk (later, R-M13)'] });
export const siteFaqSpec = siteSpec({ code: 'P-11', name: 'Website: FAQ', purpose: 'Published FAQs from site_faqs grouped by topic tabs with search; owners edit the table, not the code.', layout: ['SiteHero (soft)', 'Topic tabs + search', 'Accordion list', 'CtaBand'], data: ['site_faqs'], logic: ['where published = true, order sort_order; client-side topic and text filter.'], components: [...SITE, 'Tabs', 'Input', 'EmptyState'], rules: ['R-A05', 'R-H03'], states: ['list', 'no match', 'dark'] });
export const siteAboutSpec = siteSpec({ code: 'P-12', name: 'Website: About', purpose: 'Story and values, the team from active employees (first names and roles), the one-system note, links.', layout: ['SiteHero (soft)', 'What we believe', 'Team grid', 'Behind the app', 'CtaBand'], data: ['locations', 'employees'], logic: ['employees where status active; display_name or first name only (no PII).'], components: [...SITE, 'Avatar'], rules: ['R-L01', 'R-K01'], states: ['default', 'dark'] });
export const siteSpecs = [siteHomeSpec, siteHotelSpec, siteGroomingSpec, siteDaycareSpec, sitePricingSpec, siteLocationsSpec, siteReviewsSpec, sitePoliciesSpec, siteBookSpec, siteContactSpec, siteFaqSpec, siteAboutSpec];

// ---- Ops manual M-01..M-03 + chapters ----
const MANUAL_COMPONENTS = ['ManualChapterCard', 'ManualToc', 'ManualCallout', 'LiveBlock', 'Figure', 'MarkdownViewer', 'Card', 'Badge', 'Button', 'Input', 'Chip', 'Section', 'PageHeader'];
export const manualCoverSpec = defineSpec({ code: 'M-01', name: 'Ops manual cover', purpose: 'Business operations manual cover: what the manual is, the reading path for the current role with completion ticks, the role x chapter matrix, and every chapter by part. Chapters come from docs/ops-manual/en/*.md at build time.', layout: ['ManualSidebar (search, parts, pending)', 'Cover (stats)', 'Your reading path (role)', 'Who reads what (matrix)', 'Parts I–VI chapter grids'], data: ['training_completions', 'employees'], roles: STAFF_ROLES, logic: ['chaptersForRole(role): audience labels in front matter (all staff, front desk, groomer, manager, owner).', 'Completion = training_completions rows of the signed-in employee.', 'readingMinutes = words/180 + figures + directives.'], integrations: [], components: MANUAL_COMPONENTS, rules: ['R-X73', 'R-X74'], states: ['role with chapters', 'role without chapters', 'completed chapters'], checkedAt: W });
export const manualFallbackSpec = defineSpec({ code: 'M-02', name: 'Manual chapter (fallback)', purpose: 'Route /manual/:slug: renders the chapter when the slug exists (same as its own M-1x route) or a not-found page with every chapter card.', layout: ['ManualSidebar', 'PageHeader (not found)', 'Chapter grid'], data: ['training_completions'], roles: STAFF_ROLES, logic: ['chapterBySlug(slug) ?? not found'], integrations: [], components: MANUAL_COMPONENTS, rules: ['R-X73'], states: ['found', 'not found'], checkedAt: W });
export const manualPendingSpec = defineSpec({ code: 'M-03', name: 'Manual: pending decisions, captures and drafts', purpose: 'Auto-extracted from the chapters: every > DECISION NEEDED: callout, every [screenshot: CODE] without a capture, and draft chapters other modules dropped in docs/ops-manual/en/_pending.', layout: ['ManualSidebar', 'PageHeader', 'Decisions needed', 'Screens to capture', 'Draft chapters'], data: [], roles: STAFF_ROLES, logic: ['allDecisions(), allPlaceholders(), pendingDrafts from import.meta.glob.'], integrations: [], components: ['PageHeader', 'Section', 'Card', 'Chip', 'Badge', 'EmptyState', 'MarkdownViewer'], rules: ['R-X73'], states: ['with items', 'all clear'], checkedAt: W });

/** One spec per chapter, derived from its front matter and directives. */
export function chapterSpec(c: ManualChapter): PageSpec {
  const tables = [...new Set([...c.directives.flatMap((d) => liveDirectiveTables(d.name, d.arg)), 'training_completions'])];
  const kinds = new Set(c.segments.map((s) => s.kind));
  return defineSpec({
    code: c.code, name: `Manual: ${c.title}`, purpose: `${c.summary} Chapter ${c.number} of the ops manual (part ${c.part}) for ${c.roles.join(', ')}; in-person and online lesson recorded to training_completions.`,
    layout: ['ManualSidebar', 'ChapterHeader (code, roles, meta, rules, lesson buttons)', 'ManualToc', ...c.headings.filter((h) => h.level === 2).map((h) => h.text), 'PrevNext'],
    data: tables, roles: STAFF_ROLES,
    logic: [`Rendered from docs/ops-manual/en/${c.slug}.md: ${c.segments.length} segments (${[...kinds].join(', ')}).`, `${c.directives.length} live directive(s): ${c.directives.map((d) => `{{${d.name}${d.arg ? `:${d.arg}` : ''}}}`).join(' ') || 'none'}.`, `${c.placeholders.length} screenshot placeholder(s) resolve to docs/screenshots/<CODE>/ when captured.`, 'Recording a lesson inserts training_completions { mode online | in_person } for the signed-in employee (R-X74).'],
    integrations: [], components: MANUAL_COMPONENTS, rules: [...new Set(['R-X73', 'R-X74', ...c.rules])], states: ['reading', 'online recorded', 'in-person recorded', 'placeholder figures'], figma: c.figma, checkedAt: W,
  });
}

// ---- Front desk extras F-60..F-68 ----
export const notificationsSpec = defineSpec({ code: 'F-60', name: 'Staff notifications', purpose: 'Notifications for the signed-in staff user: vaccine proofs submitted, new app bookings, payments, messages, reviews. Unread / all tabs, kind filter, mark read on open, mark all read; the TopBar bell shows the unread count.', layout: ['PageHeader (tabs, kind filter, mark all read)', 'NotificationList (StaffNotificationRow)'], data: ['notifications'], roles: STAFF_ROLES, logic: ['where user_id = session user; unread first.', 'Rows visible while the list was open are marked read on leave (R-X78); the dot toggles read/unread.', 'relativeTime() (R-M08); kind vocabulary (R-M07).'], integrations: ['Push / email delivery later (R-M13)'], components: ['PageHeader', 'Tabs', 'Select', 'Card', 'StaffNotificationRow', 'EmptyState', 'Button'], rules: ['R-M07', 'R-M08', 'R-X78', 'R-M13'], states: ['unread', 'all', 'caught up'], figma: ['notification.png'], checkedAt: W });
export const messagesSpec = defineSpec({ code: 'F-61', name: 'Website inquiries', purpose: 'Contact-form submissions from the public website (P-10) for the current location; the desk marks them seen / replied / closed within one business day (R-X72). The customer chat inbox is F-57 (frontdesk-grooming-people).', layout: ['PageHeader', 'InquiriesTable (DataTable with status filter and row actions)'], data: ['site_inquiries'], roles: STAFF_ROLES, logic: ['Rows scoped to the current location (or all locations for owner / super admin).', 'Status flow new -> seen -> replied -> closed; replied stamps replied_by / replied_at (R-X72).', 'The public contact form (P-10) inserts rows with status new.'], integrations: ['Public website contact form (P-10)', 'Desk notification on new inquiry (later, R-M13)'], components: ['PageHeader', 'Card', 'DataTable', 'Badge', 'Button'], rules: ['R-X72', 'R-M08'], states: ['new inquiries', 'all handled', 'empty'], figma: ['message.jpg'], checkedAt: W });
export const reportsSpec = defineSpec({ code: 'F-62', name: 'Reports overview', purpose: 'KPIs for 7 / 30 / 90 days at the location scope: hotel bookings and nights, grooming appointments, daycare days, money collected (owner), collected-per-day chart, attention list (vaccine proofs, pending bookings, feedback), bookings by status.', layout: ['PageHeader (period)', 'StatTiles', 'ReportBarChart (collected per day)', 'Needs attention', 'Bookings by status table'], data: ['bookings', 'appointments', 'daycare_bookings', 'payments', 'vaccine_records', 'feedback'], roles: MGMT, logic: ['Period = last N days ending today; bookings by check_in, appointments by starts_at, daycare by date, payments by paid_at (status paid).', 'useLocation().scope: pinned location or all (R-X76); money needs reports.financial.'], integrations: [], components: ['PageHeader', 'SegmentedControl', 'StatTile', 'Card', 'ReportBarChart', 'DataTable', 'Badge', 'Button', 'Section', 'EmptyState'], rules: ['R-X76', 'R-L05', 'R-I05'], states: ['7 / 30 / 90 days', 'manager (no money)', 'owner'], figma: ['report.jpg (empty shell)', 'front desk-3.jpg (KPI cards)'], checkedAt: W });
export const revenueSpec = defineSpec({ code: 'F-63', name: 'Revenue report', purpose: 'Collected payments for the period by day, by service (hotel / grooming / daycare) and by method (card / cash), card fee and tax collected, outstanding balances, payment list, CSV export. Owner only.', layout: ['PageHeader (period, export)', 'StatTiles', 'ReportBarChart', 'By service / by method tables', 'Payments table'], data: ['payments', 'invoices'], roles: MGMT, logic: ['paid = payments.status paid && paid_at in period; service from invoices.source_type.', 'Fee and tax from invoices issued in the period; outstanding = sum(balance) of open invoices.', 'Blocked without reports.financial (EmptyState).', 'CSV built client-side.'], integrations: ['Stripe payouts reconciliation (later)'], components: ['PageHeader', 'SegmentedControl', 'StatTile', 'Card', 'ReportBarChart', 'DataTable', 'Button', 'Section', 'EmptyState'], rules: ['R-X76', 'R-L05', 'R-H03', 'R-H04'], states: ['owner', 'no permission', 'empty period'], checkedAt: W });
export const occupancySpec = defineSpec({ code: 'F-64', name: 'Occupancy report', purpose: 'Rooms occupied per night against capacity for the period, tonight per room type with a meter, room-nights sold, average stay, arrivals; cancelled and no-show excluded.', layout: ['PageHeader (period)', 'StatTiles', 'ReportBarChart (rooms per night)', 'Per room type cards (meter + mini chart)'], data: ['bookings', 'room_types', 'capacities'], roles: MGMT, logic: ['occupied(day) = live bookings with check_in <= day < check_out.', 'capacity = sum capacities.max_simultaneous for the scoped locations by room_types.key.'], integrations: [], components: ['PageHeader', 'SegmentedControl', 'StatTile', 'Card', 'ReportBarChart'], rules: ['R-X76', 'R-E11', 'R-E12'], states: ['one location', 'all locations'], checkedAt: W });
export const reviewsModSpec = defineSpec({ code: 'F-65', name: 'Reviews moderation', purpose: 'Moderation queue from reviews.jpg: pending / published / archived tabs, minimum rating filter, KPI tiles, one row per review with Approve (publish) and Archive; only published reviews reach the website.', layout: ['PageHeader (tabs, rating filter)', 'StatTiles', 'ReviewList (ReviewListItem rows)'], data: ['reviews', 'customers'], roles: MGMT, logic: ['where location scope; Approve sets status published, Archive sets archived (R-M12).', 'Buttons need reviews.moderate; others read only.'], integrations: ['Customer app "Rate your stay" writes pending reviews'], components: ['PageHeader', 'Tabs', 'Select', 'StatTile', 'Card', 'ReviewListItem', 'ReviewStars', 'Badge', 'Button', 'EmptyState', 'Toast'], rules: ['R-M12', 'R-X70'], states: ['pending', 'published', 'archived', 'read-only'], figma: ['reviews.jpg'], checkedAt: W });
export const educationSpec = defineSpec({ code: 'F-66', name: 'Education', purpose: 'Training from the ops manual: my progress per chapter (online read, in-person done, signed off) and, for managers, the team matrix where a click records a lesson or signs it off.', layout: ['PageHeader (My progress | Team)', 'StatTiles', 'My chapters list', 'Team matrix (employees x chapters)'], data: ['employees', 'training_completions'], roles: STAFF_ROLES, logic: ['Chapters and audiences from docs/ops-manual; completion rows per employee per chapter per mode (R-X74).', 'Sign-off sets signed_off_by to the manager\'s employee id; employees.read unlocks the team view.'], integrations: [], components: ['PageHeader', 'SegmentedControl', 'StatTile', 'Card', 'Badge', 'Button', 'EmptyState', 'Toast'], rules: ['R-X74', 'R-L05'], states: ['my progress', 'team matrix', 'no chapters for role'], figma: ['education.jpg (empty shell)'], checkedAt: W });
export const walkingSpec = defineSpec({ code: 'F-67', name: 'Walking', purpose: 'Walk log per day and location: dog, handler, start, minutes, potty, note; plan / start / finish / skip; checked-in hotel guests listed first when planning.', layout: ['PageHeader (day, plan)', 'StatTiles', 'Walks table (row actions)', 'Plan-a-walk Drawer'], data: ['walks', 'pets', 'customers', 'employees', 'bookings'], roles: STAFF_ROLES, logic: ['Start sets started_at now and status in_progress; Finish computes duration from the clock (min 5) and marks done (R-X75).', 'Guests in house = pets of bookings with status checked_in at the location.'], integrations: ['Daycare "Walk" price item billing (later, R-F05)'], components: ['PageHeader', 'StatTile', 'Card', 'DataTable', 'Drawer', 'DatePicker', 'Select', 'Input', 'Textarea', 'Checkbox', 'Badge', 'Avatar', 'Button', 'Toast'], rules: ['R-X75', 'R-F05'], states: ['day with walks', 'empty day', 'planning'], figma: ['employees-3.jpg (Walking shell)', 'front desk-7.jpg (Walk price)'], checkedAt: W });
export const tasksSpec = defineSpec({ code: 'F-68', name: 'Tasks & checklists', purpose: 'Management to-dos per location: checklists (opening / closing) and one-off tasks with assignee, due date, priority, status; add via drawer; delete is PIN-gated and audited.', layout: ['PageHeader (tabs, add)', 'StatTiles', 'Checklists', 'Tasks', 'Add Drawer', 'PinApprovalModal'], data: ['tasks', 'employees', 'approvals'], roles: STAFF_ROLES, logic: ['Toggle completes / reopens (completed_at); Start sets in_progress.', 'Overdue = due_on < today and not done.', 'Delete opens PinApprovalModal (action task.delete) and removes the row only after approval (R-X77, R-P01).'], integrations: [], components: ['PageHeader', 'Tabs', 'StatTile', 'Section', 'Card', 'Checkbox', 'Badge', 'Button', 'IconButton', 'Drawer', 'Input', 'Textarea', 'Select', 'DatePicker', 'PinApprovalModal', 'EmptyState', 'Toast'], rules: ['R-L07', 'R-X77', 'R-P01'], states: ['open', 'done', 'adding', 'delete approval'], figma: ['education-1.jpg (Tasks shell)', 'employees-1.jpg (Check List shell)'], checkedAt: W });
export const extrasSpecs = [notificationsSpec, messagesSpec, reportsSpec, revenueSpec, occupancySpec, reviewsModSpec, educationSpec, walkingSpec, tasksSpec];
