import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'frontdesk-reservations.today': { en: 'Front desk today', es: 'Recepción hoy' },
  'frontdesk-reservations.reservations': { en: 'Hotel & Daycare reservations', es: 'Reservas de hotel y guardería' },
  'frontdesk-reservations.timeline': { en: 'Room timeline', es: 'Cronograma de habitaciones' },
  'frontdesk-reservations.board': { en: 'Grooming & Spa board', es: 'Tablero de Grooming & Spa' },
  'frontdesk-reservations.availability': { en: 'Availability', es: 'Disponibilidad' },
  'frontdesk-reservations.newBooking': { en: 'New booking', es: 'Nueva reserva' },
  'frontdesk-reservations.arriving': { en: 'Arriving', es: 'Llegadas' },
  'frontdesk-reservations.departing': { en: 'Departing', es: 'Salidas' },
  'frontdesk-reservations.staying': { en: 'Staying', es: 'Hospedados' },
  'frontdesk-reservations.checkedOut': { en: 'Checked out', es: 'Salieron' },
  'frontdesk-reservations.daycare': { en: 'Daycare', es: 'Guardería' },
  'frontdesk-reservations.open': { en: 'Open', es: 'Abrir' },
  'frontdesk-reservations.cardActions': { en: 'Card actions', es: 'Acciones de la tarjeta' },
  'frontdesk-reservations.moveTo': { en: 'Move to {status}', es: 'Mover a {status}' },
  'frontdesk-reservations.collapseColumn': { en: 'Collapse column', es: 'Contraer columna' },
  'frontdesk-reservations.expandColumn': { en: 'Expand column', es: 'Expandir columna' },
  'frontdesk-reservations.needsPin': { en: 'Needs a manager PIN', es: 'Requiere PIN de gerente' },
  'frontdesk-reservations.noneHere': { en: 'Nothing here', es: 'Nada aquí' },
  'frontdesk-reservations.unassigned': { en: 'Unassigned', es: 'Sin asignar' },
  'frontdesk-reservations.minutes': { en: '{n} min', es: '{n} min' },
  'frontdesk-reservations.due': { en: '{amount} due', es: '{amount} por pagar' },
  'frontdesk-reservations.allRooms': { en: 'All rooms', es: 'Todas las habitaciones' },
  'frontdesk-reservations.todayPill': { en: 'Today', es: 'Hoy' },
  'frontdesk-reservations.close': { en: 'Close', es: 'Cerrar' },
  'frontdesk-reservations.noRooms': { en: 'No rooms at this location.', es: 'No hay habitaciones en esta sede.' },
  'frontdesk-reservations.roomTimeline': { en: 'Room timeline', es: 'Cronograma de habitaciones' },
};
