/* GENERATED by scripts/site-images.mjs (npm run site:images) - do not edit. */

export interface SiteImageEntry {
  /** Widths of the .webp derivatives in public/site/img, ascending; the srcset candidates. */
  widths: number[];
  /** Source pixel size, used for the img width/height attributes (aspect ratio, no layout shift). */
  w: number;
  h: number;
  /** The .jpg fallback path, relative to the document base. */
  jpg: string;
}

/** Path prefix of every derivative; a .webp candidate is `${SITE_IMG_BASE}${slug}-${width}.webp`. */
export const SITE_IMG_BASE = './site/img/';

/** The Petrock logo from the client site; PNG because it is flat art on transparency. */
export const SITE_LOGO = { png: './site/img/logo-petrock.png', png800: './site/img/logo-petrock-800.png', w: 1079, h: 324 };

export const SITE_IMAGES: Record<string, SiteImageEntry> = {
  'dsc06310': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06310-1600.jpg' },
  'dsc06358': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06358-1600.jpg' },
  'dsc06382': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06382-1600.jpg' },
  'dsc06426': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06426-1600.jpg' },
  'dsc06434': { widths: [480, 960, 1600], w: 1967, h: 1311, jpg: './site/img/dsc06434-1600.jpg' },
  'dsc06434-2': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06434-2-1600.jpg' },
  'dsc06450': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06450-1600.jpg' },
  'dsc06450-2': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06450-2-1600.jpg' },
  'dsc06464': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06464-1600.jpg' },
  'dsc06483': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06483-1600.jpg' },
  'dsc06504': { widths: [480, 960, 1600], w: 2500, h: 3750, jpg: './site/img/dsc06504-1600.jpg' },
  'dsc06592': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06592-1600.jpg' },
  'dsc06642': { widths: [480, 960, 1600], w: 2500, h: 1667, jpg: './site/img/dsc06642-1600.jpg' },
  'fullsizerender': { widths: [480, 960], w: 1558, h: 2665, jpg: './site/img/fullsizerender-1600.jpg' },
  'grooming': { widths: [480, 960], w: 1280, h: 853, jpg: './site/img/grooming-1600.jpg' },
  'img-0063': { widths: [480, 960], w: 965, h: 1288, jpg: './site/img/img-0063-1600.jpg' },
  'img-1712': { widths: [480, 960, 1600], w: 2500, h: 3333, jpg: './site/img/img-1712-1600.jpg' },
  'img-1713': { widths: [480, 960, 1600], w: 2500, h: 3333, jpg: './site/img/img-1713-1600.jpg' },
  'img-1714': { widths: [480, 960, 1600], w: 2500, h: 3333, jpg: './site/img/img-1714-1600.jpg' },
  'img-1861': { widths: [480], w: 480, h: 640, jpg: './site/img/img-1861-1600.jpg' },
  'img-1901': { widths: [480], w: 640, h: 456, jpg: './site/img/img-1901-1600.jpg' },
  'img-2145': { widths: [480, 960], w: 1170, h: 1162, jpg: './site/img/img-2145-1600.jpg' },
  'img-2146': { widths: [480, 960], w: 1170, h: 1161, jpg: './site/img/img-2146-1600.jpg' },
  'img-2147': { widths: [480, 960], w: 1170, h: 1145, jpg: './site/img/img-2147-1600.jpg' },
  'img-2148': { widths: [480, 960], w: 1170, h: 1152, jpg: './site/img/img-2148-1600.jpg' },
  'img-2149': { widths: [480, 960], w: 1170, h: 1146, jpg: './site/img/img-2149-1600.jpg' },
  'img-2150': { widths: [480, 960], w: 1170, h: 1140, jpg: './site/img/img-2150-1600.jpg' },
  'img-2234': { widths: [480], w: 480, h: 640, jpg: './site/img/img-2234-1600.jpg' },
  'img-2291': { widths: [480], w: 480, h: 640, jpg: './site/img/img-2291-1600.jpg' },
  'img-2341': { widths: [480, 960], w: 1512, h: 2016, jpg: './site/img/img-2341-1600.jpg' },
  'img-2349': { widths: [480], w: 480, h: 640, jpg: './site/img/img-2349-1600.jpg' },
  'img-2490': { widths: [480], w: 480, h: 640, jpg: './site/img/img-2490-1600.jpg' },
  'img-2600': { widths: [480], w: 480, h: 640, jpg: './site/img/img-2600-1600.jpg' },
  'img-2611': { widths: [480], w: 640, h: 480, jpg: './site/img/img-2611-1600.jpg' },
  'img-2677': { widths: [480], w: 480, h: 640, jpg: './site/img/img-2677-1600.jpg' },
  'img-3109': { widths: [480, 960], w: 1284, h: 1514, jpg: './site/img/img-3109-1600.jpg' },
  'img-3110': { widths: [480, 960], w: 1166, h: 1263, jpg: './site/img/img-3110-1600.jpg' },
  'img-3111': { widths: [480, 960], w: 1052, h: 1286, jpg: './site/img/img-3111-1600.jpg' },
  'img-3113': { widths: [480], w: 824, h: 960, jpg: './site/img/img-3113-1600.jpg' },
  'img-3114': { widths: [480, 960], w: 1284, h: 1603, jpg: './site/img/img-3114-1600.jpg' },
  'img-3323': { widths: [480], w: 480, h: 640, jpg: './site/img/img-3323-1600.jpg' },
  'img-4363': { widths: [480], w: 480, h: 640, jpg: './site/img/img-4363-1600.jpg' },
  'img-4475': { widths: [480], w: 480, h: 640, jpg: './site/img/img-4475-1600.jpg' },
  'img-4643': { widths: [480], w: 480, h: 640, jpg: './site/img/img-4643-1600.jpg' },
  'img-4949': { widths: [480], w: 480, h: 640, jpg: './site/img/img-4949-1600.jpg' },
  'img-8163': { widths: [480, 960, 1600], w: 2500, h: 3333, jpg: './site/img/img-8163-1600.jpg' },
  'img-8675': { widths: [480, 960, 1600], w: 2500, h: 3333, jpg: './site/img/img-8675-1600.jpg' },
  'img-8944': { widths: [480], w: 640, h: 480, jpg: './site/img/img-8944-1600.jpg' },
  'penthouse-photo-layout': { widths: [480, 960, 1600], w: 2500, h: 1250, jpg: './site/img/penthouse-photo-layout-1600.jpg' },
};
