import { createElement as h, useState } from 'react';
import { defineMeta } from '../../../design/meta';
import { GroomDayGrid, type GroomDayGridColumn } from './GroomDayGrid';

const day = new Date().toISOString().slice(0, 10);
const at = (hm: string) => { const [hh, mm] = hm.split(':').map(Number); const d = new Date(`${day}T12:00:00`); d.setHours(hh, mm, 0, 0); return d.toISOString(); };
function Demo() {
  const [cols, setCols] = useState<GroomDayGridColumn[]>([{ id: 'a', name: 'Itzel Diaz', color: 'var(--groomer-3)', hours: { open: '08:00', close: '15:00' } }, { id: 'b', name: 'Jessica Guzman', color: 'var(--groomer-5)', hours: { open: '09:00', close: '17:00' } }, { id: 'c', name: 'Nasim', color: 'var(--groomer-1)', hours: null }]);
  const items = [{ id: '1', columnId: 'a', startsAt: at('10:00'), durationMin: 90, label: 'Wong, TEDDY; Cairn Terrier; Diamond Groom Medium', pet: 'Teddy', breed: 'Cairn Terrier', customer: 'Wong, Alice', timeLabel: '10:00 – 11:30 AM', chips: [{ label: 'Diamond · M' }], status: 'confirmed' }, { id: '2', columnId: 'b', startsAt: at('12:00'), durationMin: 60, label: 'Ford, WOOKIE; Shih Tzu; Diamond Groom Medium', pet: 'Wookie', breed: 'Shih Tzu', customer: 'Ford, Sam', timeLabel: '12:00 – 1:00 PM', status: 'confirmed', flags: { vaccine: true } }, { id: '3', columnId: 'a', startsAt: at('12:00'), durationMin: 30, label: 'Kasher, MAX; Poodle (Miniature); Diamond Groom Small', pet: 'Max', breed: 'Mini Poodle', timeLabel: '12:00 PM', status: 'requested', flags: { warning: true } }];
  return h(GroomDayGrid, { columns: cols, items, startHour: 8, endHour: 16, hourHeight: 52, capacity: 2,
    onMoveColumn: (id, dir) => setCols((c) => { const i = c.findIndex((x) => x.id === id); const j = i + dir; if (j < 0 || j >= c.length) return c; const n = [...c]; [n[i], n[j]] = [n[j], n[i]]; return n; }),
    onColorColumn: (id, color) => setCols((c) => c.map((x) => (x.id === id ? { ...x, color: color ?? 'var(--color-border-strong)' } : x))), onHideColumn: (id, hidden) => setCols((c) => c.map((x) => (x.id === id ? { ...x, hidden } : x))) });
}
export default defineMeta({
  tier: 'organism', name: 'GroomDayGrid', description: 'Grooming day view: hourly rows x groomer columns. The head is a white cell - initials disc in the groomer\'s muted hue, name, working hours - under a thin coloured top border. Working hours are an 8 % tint, off hours a low-contrast hatch, half hours a faint line. Overlapping appointments split the column into side-by-side lanes; cards are ScheduleCards (compact). Over-capacity hours get a warning chip beside the neutral hour label (R-G21); when the day is today a dashed hairline with a time chip marks now. Column menu: move left / right, change colour (groomer-hue swatches + picker), hide. Horizontal scroll with sticky time column on phones (D-016).',
  props: [{ name: 'columns', type: 'GroomDayGridColumn[]', required: true, description: 'Groomers with colour, hidden flag and working hours' }, { name: 'items', type: 'GroomDayGridItem[]', required: true, description: 'Appointments (label, status, flags)' }, { name: 'startHour / endHour', type: 'number', default: '7 / 18', description: 'Grid range' }, { name: 'capacity', type: 'number', description: 'Warning chip on hours with more than this many overlaps' }, { name: 'showNow', type: 'boolean', default: 'true', description: 'Draw the current-time hairline (pass day === today)' }, { name: 'labels', type: 'Record<string, string>', description: 'Translated labels from the module (useT)' }, { name: 'onItemClick', type: '(id) => void', description: 'Open appointment' }, { name: 'onMoveColumn / onColorColumn / onHideColumn', type: 'fn', description: 'Column menu (R-X62)' }, { name: 'onSlotClick', type: '(columnId, HH:MM) => void', description: 'Book into an empty slot' }, { name: 'onItemMove', type: '(id, columnId, HH:MM) => void', description: 'Drag and drop reschedule' }],
  states: ['default', 'column menu open', 'colour submenu', 'groomer off today (hatched)', 'over capacity hour', 'overlapping lanes', 'now line (today)', 'unassigned column'],
  usages: [{ title: 'Three groomers', render: () => h(Demo) }],
  a11y: ['Cards are ScheduleCard buttons with the full R-G20 label as their accessible name; the column menu uses role=menu with aria-expanded and disabled edges.', 'The over-capacity chip carries an aria-label; tints, hatch and the now line are decorative.'],
  usedBy: ['F-30'], figma: ['Grooming.png', 'Grooming-1.png'],
});
